import test from 'node:test'
import assert from 'node:assert/strict'
import {fresh} from './helpers.ts'
import {createStore,updateStore} from '../src/control/stores.ts'
import {createProduct,getProduct,updateProduct,updateVariant} from '../src/domain/catalog.ts'
import {createPage,getPage,updatePage,listPageRevisions} from '../src/pages/store.ts'
import {reviewRevision,reviewSlots,validateSuggestions,getReview,rejectSuggestions,applySuggestions,undoReview,createReview as generateReview} from '../src/control/cro-review.ts'
import type {PrivatePassage} from '../src/agent/private-course.ts'
const source:PrivatePassage={id:'source-fixture',kind:'reviewed_teaching',courseId:'evolve',moduleId:'clarity',course:'Evolve',module:'Clarity',title:'Explain the message',sourcePath:'test only',sha256:'test',text:'Make the message easier to understand before asking for the sale.',topics:['pages'],qualityFlags:[],recordingId:'recording-fixture',startMs:1000,endMs:2000}
function fixture(){const{db,user}=fresh();const store=createStore(db,user.id,{name:'Hybrid test'});const page=createPage(db,store.id,{title:'Faithful imported page',mode:'html',rawHtml:'<h1>The travel bag</h1><p>A bag with a strap for daily errands.</p><button>Add to cart</button><p>Free shipping and thirty-day returns</p>',sourceUrl:'https://permitted.example/products/bag'});const product=createProduct(db,store.id,{title:'Travel bag',subtitle:'A simple bag for your daily errands.',variants:[{title:'Blue',priceCents:2900,inventory:10}]});const slots=reviewSlots(db,store.id);const suggestions=validateSuggestions({suggestions:slots.slice(0,2).map((s,i)=>({slotId:s.id,after:i===0?'Travel bag':'A bag with a strap for everyday errands.',reason:'Simpler wording preserves the meaning.',uncertainty:'This is a wording hypothesis; no conversion lift is known.',sourceId:source.id,quote:source.text}))},slots,[source]);db.insert('cro_reviews',{id:'review-test',store_id:store.id,user_id:user.id,base_revision:reviewRevision(db,store.id),approval_token:'specific-approval-token',status:'pending',suggestions,snapshots:[],applied_revision:'',limitations:[],created_at:'2026-10-02',model:'fixture',error:''});return{db,user,store,page,product,review:getReview(db,store.id,'review-test')}}
test('review slots protect policies, prices, checkout and executable content',()=>{const f=fixture();try{assert.ok(reviewSlots(f.db,f.store.id).every(s=>!s.text.includes('Free shipping')));createPage(f.db,f.store.id,{title:'Checkout',mode:'html',role:'checkout',rawHtml:'<p>This checkout text must never change</p>'});assert.ok(!reviewSlots(f.db,f.store.id).some(s=>s.text.includes('checkout text')));assert.ok(!reviewSlots(f.db,f.store.id).some(s=>s.text==='Add to cart'));}finally{f.db.handle.close()}})
test('proposal validation rejects unsafe facts, invented results, unknown targets and false quotations',()=>{const f=fixture();const slots=reviewSlots(f.db,f.store.id),base={slotId:slots[0]!.id,after:'Travel bag',reason:'Simpler wording.',uncertainty:'Needs merchant review.',sourceId:source.id,quote:source.text};try{for(const patch of[{after:'Free thirty-day returns'},{after:'Waterproof travel bag'},{after:'<script>alert()</script>'},{after:'Buy now at https://evil.example'},{quote:'Invented course advice with no matching source'},{sourceId:'invented-source'},{slotId:'other-store-slot'},{reason:'Will increase conversion by20%'}])assert.throws(()=>validateSuggestions({suggestions:[{...base,...patch}]},slots,[source]));assert.throws(()=>validateSuggestions({suggestions:[base,base]},slots,[source]));}finally{f.db.handle.close()}})
test('rejecting changes no merchant state and rejected suggestions cannot be applied',()=>{const f=fixture();try{const before=reviewRevision(f.db,f.store.id);rejectSuggestions(f.db,f.store.id,f.review.id,[f.review.suggestions[0]!.suggestionId],f.review.token);assert.equal(reviewRevision(f.db,f.store.id),before);assert.throws(()=>applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[0]!.suggestionId],f.review.token),/pending/);}finally{f.db.handle.close()}})
test('partial acceptance applies exactly one edit, preserves commerce and makes remaining proposals stale',()=>{const f=fixture();try{const variants=JSON.stringify(getProduct(f.db,f.store.id,f.product.id)!.variants);const after=applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[0]!.suggestionId],f.review.token);assert.match(getPage(f.db,f.store.id,f.page.id)!.rawHtml,/<h1>Travel bag<\/h1>/);assert.ok(getPage(f.db,f.store.id,f.page.id)!.rawHtml.includes('A bag with a strap for daily errands.'));assert.equal(JSON.stringify(getProduct(f.db,f.store.id,f.product.id)!.variants),variants);assert.equal(after.suggestions[1]!.status,'pending');assert.throws(()=>applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[1]!.suggestionId],f.review.token),/Stale/);}finally{f.db.handle.close()}})
test('a scoped batch applies all selected edits atomically and undo restores exact original HTML',()=>{const f=fixture();try{const before=f.page.rawHtml;applySuggestions(f.db,f.store.id,f.user.id,f.review.id,f.review.suggestions.map(s=>s.suggestionId),f.review.token);assert.ok(!getPage(f.db,f.store.id,f.page.id)!.rawHtml.includes('daily errands.'));undoReview(f.db,f.store.id,f.user.id,f.review.id,f.review.token);assert.equal(getPage(f.db,f.store.id,f.page.id)!.rawHtml,before);assert.equal(getReview(f.db,f.store.id,f.review.id).status,'undone');assert.ok(listPageRevisions(f.db,f.store.id,f.page.id).some(r=>r.note==='Undo accepted CRO suggestions'));}finally{f.db.handle.close()}})
test('apply failures roll back every edit and revision; retry remains possible',()=>{const f=fixture();try{const before=reviewRevision(f.db,f.store.id),revisionCount=listPageRevisions(f.db,f.store.id,f.page.id).length;assert.throws(()=>applySuggestions(f.db,f.store.id,f.user.id,f.review.id,f.review.suggestions.map(s=>s.suggestionId),f.review.token,i=>{if(i===1)throw new Error('Injected write failure')}),/Injected/);assert.equal(reviewRevision(f.db,f.store.id),before);assert.equal(getPage(f.db,f.store.id,f.page.id)!.rawHtml,f.page.rawHtml);assert.equal(listPageRevisions(f.db,f.store.id,f.page.id).length,revisionCount);assert.equal(getReview(f.db,f.store.id,f.review.id).status,'pending');applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[0]!.suggestionId],f.review.token);}finally{f.db.handle.close()}})
test('page, price, currency and asset edits invalidate old acceptance',()=>{for(const change of['page','price','currency','asset','environment']){const f=fixture();try{if(change==='page')updatePage(f.db,f.store.id,f.page.id,{rawHtml:f.page.rawHtml+'<p>Later merchant edit</p>'});if(change==='price')updateVariant(f.db,f.store.id,f.product.variants[0]!.id,{priceCents:3100});if(change==='currency')updateStore(f.db,f.store.id,{currency:'CAD'});if(change==='asset')updateProduct(f.db,f.store.id,f.product.id,{heroImage:'/new-photo.webp'});if(change==='environment')f.db.run("UPDATE store_environments SET theme='[1]' WHERE store_id=?",f.store.id);const before=reviewRevision(f.db,f.store.id);assert.throws(()=>applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[0]!.suggestionId],f.review.token),/Stale/);assert.equal(reviewRevision(f.db,f.store.id),before);}finally{f.db.handle.close()}}})
test('undo cannot overwrite later work; generic yes, wrong tokens and cross-store reviews are rejected',()=>{const f=fixture();try{assert.throws(()=>applySuggestions(f.db,f.store.id,f.user.id,f.review.id,['yes'],f.review.token),/exact pending/);assert.throws(()=>applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[0]!.suggestionId],'wrong'),/specific current/);const other=createStore(f.db,f.user.id,{name:'Other'});assert.throws(()=>getReview(f.db,other.id,f.review.id),/No review/);applySuggestions(f.db,f.store.id,f.user.id,f.review.id,[f.review.suggestions[0]!.suggestionId],f.review.token);updateProduct(f.db,f.store.id,f.product.id,{title:'Later merchant title'});assert.throws(()=>undoReview(f.db,f.store.id,f.user.id,f.review.id,f.review.token),/preserve later edits/);assert.equal(getProduct(f.db,f.store.id,f.product.id)!.title,'Later merchant title');}finally{f.db.handle.close()}})
test('unavailable course/model fails honestly without mutating merchant state',async()=>{const f=fixture();const old=process.env.STOREMILL_COURSE_MODEL_DISCLOSURE;try{delete process.env.STOREMILL_COURSE_MODEL_DISCLOSURE;const before=reviewRevision(f.db,f.store.id);await assert.rejects(generateReview(f.db,f.store.id,f.user.id,{choice:null}),/disclosure/);assert.equal(reviewRevision(f.db,f.store.id),before);}finally{if(old===undefined)delete process.env.STOREMILL_COURSE_MODEL_DISCLOSURE;else process.env.STOREMILL_COURSE_MODEL_DISCLOSURE=old;f.db.handle.close()}})
