import test from 'node:test'
import assert from 'node:assert/strict'
import { readSourceCommerce } from '../src/pages/source-commerce.ts'
import { importAssetFromUrl } from '../src/control/assets.ts'
import { defaultRegion } from '../src/domain/regions.ts'
import { duplicateAsset } from '../src/control/duplicate-asset.ts'
import { readCopyReport } from '../src/pages/clone-report.ts'
import { ensurePageRevision, updatePage, savePageRevision, restorePageRevision, listPages } from '../src/pages/store.ts'
import { fresh } from './helpers.ts'
import { groupedSource } from './fixtures/grouped-source.ts'
test('explicit grouped source keeps package, shipping and add-on prices independent without fabricating inventory',()=>{
 for(const currency of ['USD','CAD','JPY']){const {html}=groupedSource(currency),r=readSourceCommerce(html,'https://demo.example/checkout',currency);assert.equal(r.products.length,4);assert.deepEqual(r.products[0]!.product.variants.map(v=>v.priceCents),[4800,4800,8500]);assert.deepEqual(r.shipping!.map(s=>s.amountCents),[499,200,699]);assert.equal(r.products[0]!.defaultSourceId,'8');assert.equal(r.products[0]!.product.title,'Hidden source box');assert.ok(r.products.every(p=>p.product.currency===currency&&p.product.variants.every(v=>v.inventory===0&&v.allowBackorder)));assert.equal(r.products.filter(p=>p.purpose==='addon').length,3);assert.ok(r.issues.some(s=>s.includes('Hidden source selection')))}
})
test('unknown source selectors and recurring configurations are visibly blocked without partial catalog manufacture',()=>{
 const {html}=groupedSource();for(const changed of[html.replace('product-id_shipping_product','product-id_warranty_product'),html.replace('"isSub":false','"isSub":true'),html.replace('value=6','value=999'),html.replace('currency_code":"USD','currency_code":"???'),html.replace('value=9 style','value=9 checked style'),html.replace('"price":4.99','"price":4.999'),html.replace('value=1 checked','value=1'),html.replace(/<label>Delivery[\s\S]*?<\/label>/g,''),html.replace('"soldout":false','"soldout":true')]){const r=readSourceCommerce(changed,'https://demo.example/checkout','USD');assert.deepEqual(r.products,[]);assert.deepEqual(r.shipping,[]);assert.ok(r.issues.some(s=>s.includes('blocked')))}
})
test('grouped import and duplicate preserve scoped prices, defaults, input bindings and independent shipping options',async()=>{
 const{db,user}=fresh();try{const {html}=groupedSource('CAD');const imported=await importAssetFromUrl(db,user.id,{url:'https://demo.example/checkout',kind:'funnel',currency:'CAD',scope:'page',fetchImpl:async()=>new Response(html,{headers:{'content-type':'text/html'}})});assert.equal(imported.products.length,4);assert.deepEqual(defaultRegion(db,imported.store.id)!.shipping.map(s=>s.amountCents),[499,200,699]);assert.match(imported.page.rawHtml,/data-copy-choice="primary"/);assert.match(imported.page.rawHtml,/data-copy-choice="addon"/);assert.match(imported.page.rawHtml,/data-copy-choice="shipping"/);assert.ok(readCopyReport(db,imported.store.id,imported.page.id)!.site!.commerce!.issues.some(s=>s.reason.includes('Hidden source')));const copy=duplicateAsset(db,user.id,imported.store.id).store;const own=defaultRegion(db,copy.id)!;assert.deepEqual(own.shipping.map(s=>s.amountCents),[499,200,699]);assert.notEqual(own.shipping[0]!.id,defaultRegion(db,imported.store.id)!.shipping[0]!.id);assert.equal(copy.currency,'CAD');const page=listPages(db,copy.id).find(p=>p.role==='checkout')!;const before=page.rawHtml,prices=JSON.stringify(defaultRegion(db,copy.id)!.shipping),original=ensurePageRevision(db,page);const changed=updatePage(db,copy.id,page.id,{rawHtml:before.replace('Your order choices','Your copied order choices')});savePageRevision(db,changed,'Merchant copy edit');restorePageRevision(db,copy.id,page.id,original.id);assert.equal(listPages(db,copy.id).find(p=>p.id===page.id)!.rawHtml,before);assert.equal(JSON.stringify(defaultRegion(db,copy.id)!.shipping),prices);assert.equal(imported.page.rawHtml.includes('Your copied order choices'),false)}finally{db.handle.close()}
})
