import assert from 'node:assert/strict';
import test,{after} from 'node:test';
import {mkdtempSync,rmSync,existsSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium} from 'playwright';
const dir=mkdtempSync(join(tmpdir(),'copy-commerce-'));process.env.AMBORAS_DB=join(dir,'test.db');process.env.PORT='0';process.env.AMBORAS_LOG_LEVEL='error';process.env.AMBORAS_STOREFRONT_HOST='';process.env.AMBORAS_PUBLIC_ORIGIN='';process.env.AMBORAS_ADMIN_HOST='';
const originalFetch=globalThis.fetch;globalThis.fetch=(url,init)=>String(url).includes('graph.facebook.com')?Promise.resolve(new Response('{"events_received":1}')):originalFetch(url,init);
const {server}=await import('../src/main.ts');const {getDb}=await import('../src/lib/db.ts');const {register}=await import('../src/control/auth.ts');const {createStore}=await import('../src/control/stores.ts');const {createProduct}=await import('../src/domain/catalog.ts');const {createPage}=await import('../src/pages/store.ts');const {seedDefaultRegion}=await import('../src/domain/regions.ts');const {install}=await import('../src/control/plugins.ts');const {useStripeTransport,signWebhook}=await import('../src/payments/stripe.ts');
const db=getDb();const user=register(db,{email:'copy-tests@example.com',password:'test-password-long'});const store=createStore(db,user.id,{name:'Copied test shop'});seedDefaultRegion(db,store.id,'USD');db.update('stores',store.id,{status:'live'});
const product=createProduct(db,store.id,{title:'Everyday cushion',status:'published',variants:[{title:'Blue',priceCents:5495,inventory:100},{title:'Green',priceCents:5995,inventory:100}]});
const [blue,green]=product.variants;db.update('products',product.id,{metadata:{['sourceVariant:'+blue.id]:'101',['sourceVariant:'+green.id]:'102'}});
const style='<style>body{margin:0;font:16px system-ui}main{max-width:1000px;margin:auto;padding:20px}button,input,select{min-height:44px;font:inherit;max-width:100%}.no-js .no-js-hidden{display:none}.no-js-hidden img{max-width:100%}#CartDrawer{position:fixed;inset:0 0 0 auto;width:400px;max-width:100vw;background:white;z-index:99;padding:20px;box-sizing:border-box;overflow:auto}#CartDrawer:not(.active){display:none}.checkout-shell{display:grid;grid-template-columns:1fr 1fr;gap:24px;padding:20px}.checkout-shell>*{min-width:0}@media(max-width:700px){.checkout-shell{grid-template-columns:1fr}}details:not(.menu-opening) #menu-drawer{visibility:hidden}</style>';
const source='<!doctype html><html class="no-js"><head><meta name="viewport" content="width=device-width,initial-scale=1">'+style+'</head><body><header-drawer><details class="menu-drawer-container"><summary aria-label="Menu">Menu</summary><div id="menu-drawer"><a href="/collections/all">All products</a><button class="menu-drawer__close-menu-btn">Close menu</button></div></details></header-drawer><main><div class="no-js-hidden"><img width="200" height="100" src="" data-src="data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'200\' height=\'100\'%3E%3Crect width=\'200\' height=\'100\' fill=\'blue\'/%3E%3C/svg%3E"></div><h1>Everyday cushion</h1><form action="https://source.example/cart/add"><select name="id" aria-label="Color"><option value="101">Blue</option><option value="102">Green</option></select><input name="quantity" value="1" type="number" aria-label="Quantity"><button name="add" type="submit">Add to cart</button></form><a href="https://source.example/cart">Cart <span data-cart-count>0</span></a></main><cart-drawer id="CartDrawer" hidden><button class="drawer__close">Close cart</button><div id="CartDrawer-CartItems"><p>Original source item must disappear</p></div><p class="totals__subtotal-value">$0</p><a href="https://source.example/checkout">Checkout</a></cart-drawer><script>window.SOURCE_EXECUTED=true</script></body></html>';
createPage(db,store.id,{title:'Product',handle:'product-copy',sourceUrl:'https://source.example/products/cushion',productId:product.id,rawHtml:source,status:'published',role:'pdp'});
createPage(db,store.id,{title:'Copied cart',sourceUrl:'https://source.example/cart',rawHtml:'<html><head>'+style+'</head><body><main><h1>Your copied cart</h1><div data-cart-items>Stale copied items</div><p data-cart-subtotal>$99</p><a href="https://source.example/checkout">Checkout</a></main></body></html>',status:'published',role:'cart'});
createPage(db,store.id,{title:'Copied checkout',sourceUrl:'https://source.example/checkout',rawHtml:'<html><head><meta name="viewport" content="width=device-width,initial-scale=1">'+style+'</head><body><h1>Original checkout branding</h1><main class="checkout-shell"><div><input name="emailAddress" type="email" aria-label="Email"><input name="shipFirstName" aria-label="First name"><input name="shipLastName" aria-label="Last name"><input name="shipAddress1" aria-label="Address"><input name="shipAddress2" aria-label="Apartment, suite, etc."><input name="shipState" aria-label="State / province"><input name="shipCity" aria-label="City"><input name="shipPostalCode" aria-label="Postal code"><select name="shipCountry" aria-label="Country"><option value="US">US</option></select><form class="fk-card-payment-container"><input name="cardNumber"><input name="cardDate"><input name="cardSecurityCode"><button>Source pay</button></form></div><aside class="order-summary">Stale source totals</aside></main></body></html>',status:'published',role:'checkout'});
createPage(db,store.id,{title:'Rosabella controls',handle:'source-controls',sourceUrl:'https://source.example/rosabella',productId:product.id,status:'published',rawHtml:`<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}.product-gallery{width:609px;max-width:calc(100vw - 20px);margin:auto}.swiper-wrapper{display:flex}.swiper-slide{flex-shrink:0;width:609px;height:100px}.swiper{overflow:hidden}.khOfferBox{padding:20px}.activeOfferType{font-weight:bold}</style></head><body><div class="product-gallery"><div class="swiper mainImage"><div class="swiper-wrapper"><div class="swiper-slide">One</div><div class="swiper-slide">Two</div></div></div><div class="swiper thumbImage"><div class="swiper-wrapper"><div class="swiper-slide">One</div><div class="swiper-slide">Two</div></div></div></div><div><div class="oneOfferButton">One time purchase</div><div class="subOfferButton activeOfferType">Subscribe &amp; Save</div></div><div class="khSubOffer"><div class="khOfferBox of_selected_box">Subscription package</div></div><div class="khOneOffer"><div class="khOfferBox" data-copy-variant-id="${blue.id}" data-copy-product-id="${product.id}">One time small</div><div class="khOfferBox" data-copy-variant-id="${green.id}" data-copy-product-id="${product.id}">One time large</div></div><button>Add to cart</button></body></html>`});
createPage(db,store.id,{title:'Copied forms',handle:'forms-copy',sourceUrl:'https://source.example/contact',status:'published',rawHtml:`<html><body><form id="contact" action="https://source.example/contact"><input name="contact[email]" type="email" aria-label="Contact email"><input name="contact[name]" aria-label="Name"><textarea name="contact[body]" aria-label="Message"></textarea><button>Send message</button></form><form id="newsletter" action="https://source.example/contact"><input name="form_type" type="hidden" value="customer"><input type="email" name="contact[email]" aria-label="Newsletter email"><button>Subscribe</button></form><form role="search" action="https://source.example/search"><input name="search" type="search" aria-label="Search products"><button>Find products</button></form><form action="https://source.example/track"><input name="order_number" aria-label="Order number"><button>Track order</button></form></body></html>`});
createPage(db,store.id,{title:'Reusable copied section',handle:'section-in-native',mode:'blocks',productId:product.id,status:'published',blocks:[{id:'native',type:'custom-html',settings:{html:'<button id="native-action" onclick="window.NATIVE_CLICKS=(window.NATIVE_CLICKS||0)+1">Native action</button>'}},{id:'copy',type:'custom-html',settings:{sourceUrl:'https://source.example/products/cushion',html:'<section data-pb-imported-section><form action="https://source.example/cart/add"><select name="id" aria-label="Copied variant"><option value="102">Green</option></select><button name="add">Add copied product</button></form><script>window.SOURCE_SECTION_EXECUTED=true</script></section>'}},{id:'custom-code',type:'custom-code',settings:{js:'window.NATIVE_SCRIPT_LOADED=true;'}}]});
install(db,store.id,'meta-pixel',{pixelId:'1234567890',accessToken:'test-token'});
install(db,store.id,'stripe',{publishableKey:'pk_test_fixture',secretKey:'sk_test_fixture',webhookSecret:'whsec_fixture'});
const intents=new Map();let seq=0;const providerCalls=[];
useStripeTransport(async(path,init)=>{providerCalls.push({path,method:init.method});if(path==='/v1/customers')return {ok:true,status:200,json:async()=>({id:'cus_fixture'})};let intent;if(path==='/v1/payment_intents'){const data=new URLSearchParams(init.body);intent={id:'pi_fixture_'+(++seq),status:'requires_payment_method',amount:Number(data.get('amount')),currency:data.get('currency'),metadata:{storeId:data.get('metadata[storeId]'),cartId:data.get('metadata[cartId]')}};intent.client_secret=intent.id+'_secret';intents.set(intent.id,intent);}else{intent=intents.get(path.split('/').at(-1));if(init.method==='POST'&&intent){const data=new URLSearchParams(init.body);intent.amount=Number(data.get('amount')||intent.amount);}}return {ok:!!intent,status:intent?200:404,json:async()=>intent||{error:{message:'No test intent'}}};});
await new Promise(resolve=>server.listening?resolve():server.once('listening',resolve));const origin='http://127.0.0.1:'+server.address().port;const base='/s/'+store.slug;
const browser=await chromium.launch({headless:true,...(existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
after(async()=>{await browser.close();await new Promise(resolve=>server.close(resolve));useStripeTransport(null);globalThis.fetch=originalFetch;rmSync(dir,{recursive:true,force:true});});
await test('imported commerce browser workflows',async t=>{
for(const width of [390,820,1440])await t.test('imported commerce works at '+width+'px with our cart and mocked Stripe',async()=>{
 const context=await browser.newContext({viewport:{width,height:1000}});await context.route('**/connect.facebook.net/**',route=>route.fulfill({contentType:'application/javascript',body:''}));await context.addCookies([{name:'_fbp',value:'fb.1.1234567890123.456789',url:origin},{name:'_fbc',value:'fb.1.1234567890123.click-id',url:origin}]);const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await context.route('https://js.stripe.com/v3/',route=>route.fulfill({contentType:'text/javascript',body:`window.Stripe=function(key){window.STRIPE_KEY=key;return {elements:function(){return {create:function(){return {mount:function(selector){document.querySelector(selector).textContent='Secure test element'},on:function(){}}},submit:async()=>({}),update:function(){}}},confirmPayment:async function(input){window.LAST_CONFIRM=input;return {error:{message:'Test decline: no money moved'}}}}};` }));
 await page.goto(origin+base+'/pages/product-copy');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY,{},{timeout:5000}).catch(async error=>{console.log('PAGE DEBUG',page.url(),errors,(await page.content()).slice(0,2000));throw error;});
 assert.equal(await page.evaluate(()=>window.SOURCE_EXECUTED),undefined);assert.equal(await page.locator('.no-js-hidden').isVisible(),true);assert.ok(await page.locator('img').getAttribute('src'));
 await page.locator('summary').click();await page.waitForFunction(()=>document.querySelector('details').classList.contains('menu-opening'));assert.equal(await page.locator('#menu-drawer').isVisible(),true);await page.locator('.menu-drawer__close-menu-btn').click();
 await page.getByLabel('Color').selectOption('102');await page.getByRole('button',{name:'Add to cart',exact:true}).click();await page.locator('[data-owned-cart-line]').waitFor();
 assert.match(await page.locator('[data-owned-cart-line]').textContent(),/Green/);assert.equal(await page.locator('[data-owned-cart-line]').count(),1);assert.doesNotMatch(await page.locator('#CartDrawer').textContent(),/Original source item/);
 await page.locator('[data-copy-quantity]').fill('2');await page.locator('[data-copy-quantity]').dispatchEvent('change');await page.waitForFunction(()=>document.querySelector('[data-cart-count]').textContent==='2');
 const state=await page.request.get(origin+base+'/cart/state').then(r=>r.json());assert.equal(state.items[0].variantId,green.id);assert.equal(state.items[0].lineCents,11990);
 await page.keyboard.press('Escape');assert.equal(await page.locator('#CartDrawer').isVisible(),false);await page.getByRole('link',{name:/Cart/}).click();await page.locator('#CartDrawer').getByRole('link',{name:'Checkout'}).click();await page.locator('#checkout-form').waitFor();
 assert.match(await page.locator('h1').textContent(),/Original checkout branding/);assert.equal(await page.locator('input[autocomplete="cc-number"],input[name=cardNumber],input[name=cardDate],input[name=cardSecurityCode]').count(),0);assert.equal(await page.locator('#checkout-form').getAttribute('action'),base+'/checkout');await page.waitForFunction(()=>window.STRIPE_KEY==='pk_test_fixture',{},{timeout:5000}).catch(async error=>{console.log('STRIPE DEBUG',errors,await page.locator('script').evaluateAll(nodes=>nodes.map(node=>({src:node.src,text:node.textContent.slice(0,180)}))));throw error;});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
 await page.getByLabel('Email',{exact:true}).fill('shopper-'+width+'@example.com');await page.getByLabel('First name',{exact:true}).fill('Test');await page.getByLabel('Last name',{exact:true}).fill('Shopper');await page.getByLabel('Address',{exact:true}).fill('1 Main Street');await page.getByLabel('City',{exact:true}).fill('Phoenix');await page.getByLabel('Postal code',{exact:true}).fill('85001');await page.getByLabel('Apartment, suite, etc.',{exact:true}).fill(' Suite 204 ');await page.getByLabel('State / province',{exact:true}).fill(' AZ ');assert.equal(await page.getByLabel('Apartment, suite, etc.',{exact:true}).getAttribute('required'),null);assert.equal(await page.getByLabel('State / province',{exact:true}).getAttribute('required'),null);await page.locator('#pay').click();await page.getByText('Test decline: no money moved').waitFor();assert.equal(await page.locator('#pay').isEnabled(),true);
 const confirmation=await page.evaluate(()=>({secret:window.LAST_CONFIRM.clientSecret,returnUrl:window.LAST_CONFIRM.confirmParams.return_url}));assert.match(confirmation.secret,/^pi_fixture_/);assert.equal(confirmation.returnUrl,origin+base+'/checkout/complete');
 const intent=intents.get(confirmation.secret.replace(/_secret$/,''));const savedDraft=JSON.parse(db.one('SELECT checkout FROM carts WHERE id=?',intent.metadata.cartId).checkout);assert.equal(savedDraft.address.line2,'Suite 204');assert.equal(savedDraft.address.state,'AZ');assert.equal(savedDraft.advertising.fbp,'fb.1.1234567890123.456789');assert.equal(savedDraft.advertising.url,origin+base+'/checkout');await page.reload();await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);assert.equal(await page.getByLabel('Apartment, suite, etc.',{exact:true}).inputValue(),'Suite 204');assert.equal(await page.getByLabel('State / province',{exact:true}).inputValue(),'AZ');intent.status='succeeded';const payload=JSON.stringify({type:'payment_intent.succeeded',data:{object:{id:intent.id}}});const webhook=await page.request.post(origin+base+'/webhooks/stripe',{data:payload,headers:{'content-type':'application/json','stripe-signature':signWebhook(payload,'whsec_fixture'),'user-agent':'Stripe/webhook-test'}});assert.equal(webhook.status(),200);assert.equal((await webhook.json()).matched,true);
 const paidOrderId=db.one('SELECT id FROM orders WHERE payment_intent_id=?',intent.id).id;const capi=JSON.parse(db.one("SELECT payload FROM server_event_deliveries WHERE provider='meta' AND event_id=?",paidOrderId).payload);assert.equal(capi.user_data.client_user_agent,savedDraft.advertising.userAgent);assert.notEqual(capi.user_data.client_user_agent,'Stripe/webhook-test');assert.equal(capi.user_data.fbp,savedDraft.advertising.fbp);assert.equal(capi.event_source_url,origin+base+'/checkout');
 const orderCount=db.one('SELECT COUNT(*) c FROM orders WHERE payment_intent_id = ?',intent.id).c;assert.equal(orderCount,1);const persistedAddress=JSON.parse(db.one('SELECT address FROM orders WHERE payment_intent_id=?',intent.id).address);assert.equal(persistedAddress.line2,'Suite 204');assert.equal(persistedAddress.state,'AZ');
 if(width===390){const admin=await browser.newContext();const login=await admin.request.post(origin+'/login',{form:{email:'copy-tests@example.com',password:'test-password-long'},maxRedirects:0});assert.equal(login.headers().location,'/admin');const orderId=db.one('SELECT id FROM orders WHERE payment_intent_id=?',intent.id).id;const fulfillment=await admin.request.get(origin+'/admin/orders/'+orderId);assert.equal(fulfillment.status(),200);const detail=await fulfillment.text();assert.match(detail,/Suite 204/);assert.match(detail,/Phoenix, AZ/);await admin.close();}
 const completed=await page.request.get(origin+base+'/checkout/complete?payment_intent='+intent.id,{maxRedirects:0});assert.equal(completed.status(),302);assert.match(completed.headers().location,/\/orders\//);
 assert.deepEqual(errors,[]);await context.close();
});

await t.test('copied Shopify search modal closes with its button and Escape and searches owned products',async()=>{
  for(const width of [390,820,1440]){
    const context=await browser.newContext({viewport:{width,height:1000}});const page=await context.newPage();
    await context.route('**/pages/product-copy',async route=>{const response=await route.fetch();const html=(await response.text()).replace('</header-drawer>','</header-drawer><details-modal class="header__search"><details><summary aria-label="Search">Search</summary><div class="search-modal"><form action="'+base+'/search" method="get"><input name="q" type="search" aria-label="Search catalog"><button type="submit">Submit search</button><button type="button" class="search-modal__close-button">Close search</button></form></div></details></details-modal>');await route.fulfill({response,body:html});});
    await page.goto(origin+base+'/pages/product-copy');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);const summary=page.getByLabel('Search',{exact:true});const modal=page.locator('.search-modal');
    await summary.click();assert.equal(await modal.isVisible(),true);await page.getByRole('button',{name:'Close search',exact:true}).click();assert.equal(await modal.isVisible(),false);assert.equal(await summary.evaluate(node=>node===document.activeElement),true);
    await summary.click();await page.getByLabel('Search catalog').focus();await page.keyboard.press('Escape');assert.equal(await modal.isVisible(),false);assert.equal(await summary.evaluate(node=>node===document.activeElement),true);
    await summary.click();await page.getByLabel('Search catalog').fill('cushion');await page.getByRole('button',{name:'Submit search'}).click();await page.waitForURL('**/search?q=cushion');assert.ok(await page.getByRole('link',{name:/Everyday cushion/}).count());await context.close();
  }
});

await t.test('Rosabella source gallery sizing, offer tabs, package mapping and subscription safety',async()=>{
  const context=await browser.newContext({viewport:{width:390,height:1000}});const page=await context.newPage();await page.goto(origin+base+'/pages/source-controls');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);
  const size=await page.locator('.mainImage .swiper-slide').first().evaluate(node=>node.getBoundingClientRect().width);assert.ok(Math.abs(size-320.17)<1,'source mobile uses1.15slides with12pxgap');
  assert.equal(await page.locator('.khSubOffer').isVisible(),true);assert.equal(await page.locator('.khOneOffer').isVisible(),false);
  await page.getByRole('button',{name:'Add to cart'}).click();await page.getByRole('status').getByText(/Subscriptions are not available/).waitFor();
  await page.getByRole('tab',{name:'One time purchase'}).click();assert.equal(await page.locator('.khSubOffer').isVisible(),false);assert.equal(await page.locator('.khOneOffer').isVisible(),true);
  await page.getByRole('radio',{name:'One time large'}).press('Enter');assert.equal(await page.getByRole('radio',{name:'One time large'}).getAttribute('aria-checked'),'true');
  await page.getByRole('button',{name:'Add to cart'}).click();await page.waitForURL('**/cart');const state=await page.request.get(origin+base+'/cart/state').then(r=>r.json());assert.equal(state.items[0].variantId,green.id);assert.equal(state.items[0].quantity,1);
  await page.goto(origin+base+'/pages/source-controls');await page.setViewportSize({width:1440,height:1000});await page.waitForFunction(()=>Math.abs(document.querySelector('.thumbImage .swiper-slide').getBoundingClientRect().width-113.8)<1);await context.close();
});
await t.test('copied contact, newsletter, search and tracking forms preserve intent and use owned routes',async()=>{
  const context=await browser.newContext();const page=await context.newPage();await page.goto(origin+base+'/pages/forms-copy');
  assert.equal(await page.locator('#contact').getAttribute('action'),base+'/contact');assert.equal(await page.locator('#newsletter').getAttribute('action'),base+'/subscribe');
  await page.getByLabel('Contact email').fill('contact-only@example.com');await page.getByLabel('Name',{exact:true}).fill('Contact reader');await page.getByLabel('Message').fill('Please help with my cushion');await page.getByRole('button',{name:'Send message'}).click();await page.waitForURL('**/contact');assert.equal(db.one('SELECT marketing FROM customers WHERE email = ?', 'contact-only@example.com').marketing,0);
  await page.goto(origin+base+'/pages/forms-copy');await page.getByLabel('Newsletter email').fill('opted-in@example.com');await page.getByRole('button',{name:'Subscribe',exact:true}).click();await page.waitForURL('**/subscribe');assert.equal(db.one('SELECT marketing FROM customers WHERE email = ?', 'opted-in@example.com').marketing,1);
  await page.goto(origin+base+'/pages/forms-copy');await page.getByLabel('Search products').fill('cushion');await page.getByRole('button',{name:'Find products'}).click();await page.waitForURL('**/search?q=cushion');assert.ok(await page.getByRole('link',{name:/Everyday cushion/}).count());
  await page.goto(origin+base+'/pages/forms-copy');assert.equal(await page.locator('form[action$="/track"]').getAttribute('method'),'get');assert.equal(await page.getByLabel('Order number').getAttribute('name'),'order');await context.close();
});

await t.test('manual capture and an already authorized intent never silently open an automatic charge',async()=>{
  const context=await browser.newContext();const settingsRow=db.one("SELECT id,settings FROM store_plugins WHERE store_id=? AND plugin_id='stripe'",store.id);const original=JSON.parse(settingsRow.settings);db.update('store_plugins',settingsRow.id,{settings:{...original,captureMode:'manual'}});
  const before=providerCalls.length;const blocked=await context.request.post(origin+base+'/checkout/intent',{data:{}}).then(r=>r.json());assert.match(blocked.error,/Manual capture is not supported/);assert.equal(providerCalls.length,before);db.update('store_plugins',settingsRow.id,{settings:original});
  await context.request.post(origin+base+'/cart/add',{headers:{accept:'application/json'},data:{variantId:blue.id,quantity:1}});
  const created=await context.request.post(origin+base+'/checkout/intent',{data:{}}).then(r=>r.json());assert.ok(created.intentId);intents.get(created.intentId).status='requires_capture';const count=seq;const pending=await context.request.post(origin+base+'/checkout/intent',{data:{}}).then(r=>r.json());assert.match(pending.error,/already has a payment in progress/);assert.equal(seq,count);await context.close();
});


await t.test('saved copied sections work inside native pages without replacing native scripts or actions',async()=>{
  const context=await browser.newContext();const page=await context.newPage();await page.goto(origin+base+'/pages/section-in-native');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);
  assert.equal(await page.evaluate(()=>window.SOURCE_SECTION_EXECUTED),undefined);assert.equal(await page.evaluate(()=>window.NATIVE_SCRIPT_LOADED),true);await page.getByRole('button',{name:'Native action'}).click();assert.equal(await page.evaluate(()=>window.NATIVE_CLICKS),1);
  await page.getByRole('button',{name:'Add copied product'}).click();await page.waitForURL('**/cart');const state=await page.request.get(origin+base+'/cart/state').then(r=>r.json());assert.equal(state.items[0].variantId,green.id);await context.close();
});

await t.test('source option radios override a stale hidden variant id and quantity buttons work',async()=>{
  const context=await browser.newContext();const page=await context.newPage();await page.goto(origin+base+'/pages/product-copy');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);
  await page.locator('select[name=id]').evaluate(node=>{node.outerHTML='<input type="hidden" name="id" value="101"><label><input type="radio" name="options[Color]" value="Blue" checked>Blue choice</label><label><input type="radio" name="options[Color]" value="Green">Green choice</label>';});
  await page.locator('input[name=quantity]').evaluate(node=>{const wrapper=document.createElement('div');wrapper.className='quantity';node.before(wrapper);wrapper.append(node);const button=document.createElement('button');button.type='button';button.name='plus';button.className='quantity__button';button.textContent='Increase quantity';wrapper.append(button);});
  await page.getByLabel('Green choice').check();await page.getByRole('button',{name:'Increase quantity'}).click();await page.getByRole('button',{name:'Add to cart',exact:true}).click();await page.locator('[data-owned-cart-line]').waitFor();const state=await page.request.get(origin+base+'/cart/state').then(r=>r.json());assert.equal(state.items[0].variantId,green.id);assert.equal(state.items[0].quantity,2);await context.close();
});
if(process.env.IMPORTED_CHECKOUT_FIXTURE)await t.test('actual imported Funnelish checkout has one visible secure form and no overflow',async()=>{
  db.run("UPDATE pages SET status='draft' WHERE store_id=? AND role='checkout'",store.id);
  createPage(db,store.id,{title:'Actual source checkout',sourceUrl:'https://get.tryrosabella.com/beetroot/gn/of',role:'checkout',rawHtml:readFileSync(process.env.IMPORTED_CHECKOUT_FIXTURE,'utf8'),status:'published'});
  for(const width of [1440,820,390,320]){
    const context=await browser.newContext({viewport:{width,height:1000}});await context.route('https://js.stripe.com/v3/',route=>route.fulfill({contentType:'text/javascript',body:`window.Stripe=function(){return {elements:function(){return {create:function(){return {mount:function(){},on:function(){}}},submit:async()=>({}),update:function(){}}},confirmPayment:async()=>({})}};`}));
    await context.request.post(origin+base+'/cart/add',{headers:{accept:'application/json'},data:{variantId:blue.id,quantity:1}});const page=await context.newPage();await page.goto(origin+base+'/checkout');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);
    assert.equal(await page.locator('#checkout-form').count(),1);assert.equal(await page.locator('#checkout-form [name=email]').isVisible(),true);assert.equal(await page.locator('#pay').isVisible(),true);const controls=await page.locator('#checkout-form input:not([type=hidden]),#checkout-form select').evaluateAll(nodes=>nodes.map(node=>({type:node.type,name:node.name,x:node.getBoundingClientRect().x,right:node.getBoundingClientRect().right,width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height})));assert.ok(controls.every(control=>control.x>=0&&control.right<=width+1),'all active controls within viewport');assert.ok(controls.filter(control=>!['checkbox','radio'].includes(control.type)).every(control=>control.width>=100&&control.height>=44),'text inputs retain usable dimensions');assert.ok(controls.filter(control=>control.type==='checkbox').every(control=>control.width<=24),'checkboxes do not stretch across the row');assert.equal(await page.locator('input[name=cardNumber],input[name=cardDate],input[name=cardSecurityCode],input[name=product]').count(),0);const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.body.querySelectorAll('*')].filter(n=>n.getBoundingClientRect().right>innerWidth+2||(n.clientWidth>0&&n.scrollWidth>n.clientWidth+5)).slice(0,18).map(n=>({tag:n.tagName,id:n.id,cls:n.className,width:n.getBoundingClientRect().width,right:n.getBoundingClientRect().right,style:getComputedStyle(n).width,scroll:n.scrollWidth,client:n.clientWidth,text:n.tagName==='SCRIPT'?'':n.textContent.slice(0,100),before:{width:getComputedStyle(n,'::before').width,position:getComputedStyle(n,'::before').position},after:{width:getComputedStyle(n,'::after').width,position:getComputedStyle(n,'::after').position}}))}));if(overflow.scroll>width+1)console.log('SOURCE CHECKOUT OVERFLOW',JSON.stringify(overflow));assert.ok(overflow.scroll<=width+1,'no horizontal overflow at '+width);await context.close();
  }
});

});
