import assert from 'node:assert/strict'
import test, { after } from 'node:test'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { execFileSync } from 'node:child_process'
const dir = mkdtempSync(join(tmpdir(), 'media-rebrand-test-'))
Object.assign(process.env, { AMBORAS_DB: join(dir, 'test.db'), AMBORAS_LOG_LEVEL: 'error', OPENAI_API_KEY: 'test-key', GEMINI_API_KEY: '', RUNWAYML_API_SECRET: 'test-runway' })
const { Db } = await import('../src/lib/db.ts')
const { register } = await import('../src/control/auth.ts')
const { createBlankAsset } = await import('../src/control/assets.ts')
const { duplicateAsset } = await import('../src/control/duplicate-asset.ts')
const { createProduct } = await import('../src/domain/catalog.ts')
const { createPage } = await import('../src/pages/store.ts')
const { saveUpload, saveMediaUpload, readUpload, listUploads } = await import('../src/lib/uploads.ts')
const { listStoreMedia, setMediaDetails } = await import('../src/control/media.ts')
const { replaceMediaHtml } = await import('../src/control/media-references.ts')
const { startRebrand, getRebrand, drainRebrands, cancelRebrand, applyRebrand, rebrandChanges, changesToken, undoRebrand } = await import('../src/control/media-rebrand.ts')
const { useMediaTransport } = await import('../src/control/media-render.ts')
const db = new Db(':memory:'), user = register(db, { email: 'rebrand@test.example', password: 'long-testing-password' })
const run = (args: string[]) => execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...args])
run(['-f', 'lavfi', '-i', 'color=c=blue:s=640x360', '-frames:v', '1', join(dir, 'source.png')])
run(['-f', 'lavfi', '-i', 'color=c=red:s=100x50', '-frames:v', '1', join(dir, 'logo.png')])
run(['-f', 'lavfi', '-i', 'color=c=blue:s=640x360:r=24:d=2.5', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2.5', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', join(dir, 'source.mp4')])
const png = readFileSync(join(dir, 'source.png')), red = readFileSync(join(dir, 'logo.png')), video = readFileSync(join(dir, 'source.mp4'))
after(() => { useMediaTransport(null); db.handle.close(); rmSync(dir, { recursive: true, force: true }) })
function fixture() {
 const store = createBlankAsset(db, user.id, { name: 'Desired Brand', kind: 'store', currency: 'USD' })
 const source = saveUpload({ name: 'source.png', type: 'image/png', data: png }, store.id).url
 const logo = saveUpload({ name: 'logo.png', type: 'image/png', data: red }, store.id).url
 const clip = saveMediaUpload({ name: 'source.mp4', type: 'video/mp4', data: video }, store.id).url
 const page = createPage(db, store.id, { title: 'Copied page', mode: 'html', rawHtml: `<html><body><p>${source}</p><a href="${source}">Download original</a><picture><source srcset="${source} 1x, https://example.com/large.png 2x"><img src="${source}" data-src="${source}"></picture><video controls src="${clip}" poster="${source}"></video></body></html>` })
 const product = createProduct(db, store.id, { title: 'Bottle', heroImage: source, variants: [{ title: 'Default', priceCents: 1000 }] })
 return { store, source, logo, clip, page, product }
}
await test('media rebranding', async t => {
 await t.test('finds separate responsive images, videos, posters and embedded players', () => {
  const f = fixture()
  createPage(db, f.store.id, { title: 'Remote media', mode: 'html', rawHtml: '<img src="https://example.com/a.png?w=640&amp;x=1" srcset="https://example.com/a.png?w=320 320w, https://example.com/a.png?w=640 640w"><video><source src="https://example.com/play?id=3" type="video/mp4"></video><iframe src="https://www.youtube.com/embed/abc"></iframe>' })
  const media = listStoreMedia(db, f.store.id)
  assert.equal(media.find(m => m.url === f.clip)?.kind, 'video')
  assert.equal(media.find(m => m.url === f.source)?.kind, 'image')
  assert.ok(media.some(m => m.url === 'https://example.com/a.png?w=640&x=1'))
  assert.ok(media.some(m => m.url === 'https://example.com/a.png?w=320'))
  assert.equal(media.find(m => m.url === 'https://example.com/play?id=3')?.kind, 'video')
  assert.equal(media.find(m => m.url.includes('youtube.com'))?.kind, 'embed')
  assert.ok(!media.some(m => m.url.includes(' 320w')))
 })
 await t.test('replacement handles responsive alternatives without rewriting prose, links or video posters', () => {
  const html = '<p>old.png</p><a href="old.png">old.png</a><picture><source srcset="small.png 320w, old.png 640w"><img src="fallback.png"></picture><video src="clip.mp4" poster="old.png"></video>'
  const image = replaceMediaHtml(html, 'old.png', '/_uploads/new.png')
  assert.match(image, /<p>old.png<\/p><a href="old.png">old.png<\/a>/)
  assert.match(image, /srcset="\/_uploads\/new.png 320w, \/_uploads\/new.png 640w"/)
  assert.match(image, /<img src="\/_uploads\/new.png">/)
  assert.match(image, /<video src="clip.mp4" poster="\/_uploads\/new.png">/)
  assert.match(replaceMediaHtml(html, 'clip.mp4', '/new.mp4'), /poster="old.png"/)
 })
 await t.test('duplicates video files into the new asset and rejects foreign media/logo requests', () => {
  const f = fixture(), copy = duplicateAsset(db, user.id, f.store.id)
  const copiedStoreId = (copy as any).store?.id ?? (copy as any).asset?.id ?? (copy as any).id
  assert.ok(copiedStoreId, JSON.stringify(Object.keys(copy)))
  const clips = listUploads(copiedStoreId).filter(m => m.type === 'video/mp4')
  assert.equal(clips.length, 1); assert.ok(!clips[0]!.url.includes(f.store.id))
  assert.deepEqual(readUpload(clips[0]!.url)!.data, video)
  assert.throws(() => startRebrand(db, copiedStoreId, user.id, f.source, { method: 'overlay', logo: f.logo }), /Choose an image/)
  const target = fixture()
  assert.throws(() => startRebrand(db, target.store.id, user.id, target.source, { method: 'overlay', logo: f.logo }), /Upload the desired logo/)
 })
 await t.test('logo categorization survives a full asset duplicate and rejects videos and foreign files', () => {
  const f=fixture(),other=fixture()
  setMediaDetails(db,f.store.id,f.logo,'logo','Primary logo')
  const copy=duplicateAsset(db,user.id,f.store.id)
  const logos=listStoreMedia(db,copy.store.id).filter(item=>item.category==='logo')
  assert.equal(logos.length,1);assert.equal(logos[0]!.label,'Primary logo')
  assert.ok(logos[0]!.url.startsWith('/_uploads/'+copy.store.id+'/'))
  assert.deepEqual(readUpload(logos[0]!.url)!.data,red)
  setMediaDetails(db,f.store.id,f.logo,'media','Reference')
  assert.equal(listStoreMedia(db,f.store.id).find(item=>item.url===f.logo)!.category,'media')
  assert.throws(()=>setMediaDetails(db,f.store.id,f.clip,'logo'),/must be images/)
  assert.throws(()=>setMediaDetails(db,other.store.id,f.logo,'logo'),/from this asset/)
 })
 await t.test('centered video overlay can mute source audio while retaining duration', async () => {
  const f=fixture(),job=startRebrand(db,f.store.id,user.id,f.clip,{method:'overlay',logo:f.logo,position:'center',audio:'mute'})
  await drainRebrands(db)
  const ready=getRebrand(db,f.store.id,job.id);assert.equal(ready.status,'review',ready.error)
  writeFileSync(join(dir,'muted.mp4'),readUpload(ready.result_url)!.data)
  const info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-show_format','-of','json',join(dir,'muted.mp4')]).toString())
  assert.ok(!info.streams.some((stream:any)=>stream.codec_type==='audio'))
  assert.ok(Math.abs(Number(info.format.duration)-2.5)<.2)
  const pixel=run(['-i',join(dir,'muted.mp4'),'-frames:v','1','-vf','format=rgb24,crop=1:1:320:180','-f','rawvideo','pipe:1'])
  assert.ok(pixel[0]!>200&&pixel[2]!<40,'Logo covers the center of the video')
 })
 await t.test('actual image overlay preserves dimensions and places the exact logo; apply and undo stay in this store', async () => {
  const f = fixture(), other = fixture()
  const options = { method: 'overlay' as const, logo: f.logo, brandName: 'My new brand' }
  const job = startRebrand(db, f.store.id, user.id, f.source, options)
  assert.equal(startRebrand(db, f.store.id, user.id, f.source, options).id, job.id)
  await drainRebrands(db)
  const ready = getRebrand(db, f.store.id, job.id)
  assert.equal(ready.status, 'review', ready.error)
  const output = readUpload(ready.result_url)!; writeFileSync(join(dir, 'rendered.png'), output.data)
  const sample = run(['-i', join(dir, 'rendered.png'), '-vf', 'crop=1:1:580:330,format=rgb24', '-f', 'rawvideo', 'pipe:1'])
  assert.ok(sample[0]! > 230 && sample[2]! < 20, `Logo pixel ${sample.toString('hex')}`)
  const before = db.one<{ raw_html: string }>('SELECT raw_html FROM pages WHERE id=?', f.page.id)!.raw_html
  const changes = rebrandChanges(db, f.store.id, f.source, ready.result_url)
  assert.ok(changes.length >= 2)
  assert.throws(() => applyRebrand(db, f.store.id, user.id, job.id, 'stale'), /changed since/)
  applyRebrand(db, f.store.id, user.id, job.id, changesToken(changes))
  assert.match(db.one<{ raw_html: string }>('SELECT raw_html FROM pages WHERE id=?', f.page.id)!.raw_html, new RegExp(ready.result_url))
  assert.equal(db.one<{ hero_image: string }>('SELECT hero_image FROM products WHERE id=?', other.product.id)!.hero_image, other.source)
  assert.ok(db.one<{ n: number }>('SELECT COUNT(*) n FROM page_revisions WHERE page_id=?', f.page.id)!.n >= 3)
  undoRebrand(db, f.store.id, user.id, job.id)
  assert.equal(db.one<{ raw_html: string }>('SELECT raw_html FROM pages WHERE id=?', f.page.id)!.raw_html, before)
  assert.deepEqual(readUpload(f.source)!.data, png)
 })
 await t.test('actual video overlay preserves audio and full duration', async () => {
  const f = fixture(), job = startRebrand(db, f.store.id, user.id, f.clip, { method: 'overlay', logo: f.logo })
  await drainRebrands(db)
  const ready = getRebrand(db, f.store.id, job.id); assert.equal(ready.status, 'review', ready.error)
  writeFileSync(join(dir, 'rendered.mp4'), readUpload(ready.result_url)!.data)
  const info = JSON.parse(execFileSync('ffprobe', ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', join(dir, 'rendered.mp4')]).toString())
  assert.ok(info.streams.some((stream: any) => stream.codec_type === 'audio'))
  assert.ok(Math.abs(Number(info.format.duration) - 2.5) < .2)
 })
 await t.test('AI images send the original and desired logo as separate references and persist the preview', async () => {
  const f = fixture(); let calls = 0
  useMediaTransport(async (url, init) => {
   calls++; assert.equal(url, 'https://api.openai.com/v1/images/edits')
   const form = init.body as FormData; assert.equal(form.getAll('image[]').length, 2)
   assert.match(String(form.get('prompt')), /My brand/); assert.match(String(form.get('prompt')), /Old brand/)
   assert.equal(form.get('size'), 'auto')
   return Response.json({ data: [{ b64_json: png.toString('base64') }] })
  })
  const job = startRebrand(db, f.store.id, user.id, f.source, { method: 'ai', provider: 'openai', logo: f.logo, brandName: 'My brand', oldBrand: 'Old brand' })
  await drainRebrands(db); const ready = getRebrand(db, f.store.id, job.id)
  assert.equal(ready.status, 'review', ready.error); assert.equal(calls, 1); assert.ok(readUpload(ready.result_url))
  useMediaTransport(null)
 })
 await t.test('AI video persists task ID, polls output, and restores source audio', async () => {
  const f = fixture(); const requests: string[] = []
  useMediaTransport(async (url, init) => {
   requests.push(url)
   if (url.endsWith('/images/edits')) return Response.json({ data: [{ b64_json: png.toString('base64') }] })
   if (url.endsWith('/video_to_video')) { const body = JSON.parse(String(init.body)); assert.equal(body.model, 'aleph2'); assert.equal(body.keyframes[0].seconds, .5); assert.match(body.videoUri, /^data:video\/mp4/); return Response.json({ id: 'provider-task-1' }) }
   if (url.endsWith('/tasks/provider-task-1')) return Response.json({ status: 'SUCCEEDED', output: ['https://example.com/result.mp4'] })
   if (url.endsWith('/result.mp4')) return new Response(new Uint8Array(video), { headers: { 'Content-Type': 'video/mp4' } })
   throw new Error('Unexpected provider request ' + url)
  })
  const job = startRebrand(db, f.store.id, user.id, f.clip, { method: 'ai', provider: 'openai', logo: f.logo, frame: .5 })
  await drainRebrands(db); const ready = getRebrand(db, f.store.id, job.id)
  assert.equal(ready.status, 'review', ready.error); assert.equal(ready.provider_task, 'provider-task-1'); assert.equal(requests.length, 4)
  useMediaTransport(null)
 })
 await t.test('provider failures remain failures, cancel prevents execution, and undo protects newer edits', async () => {
  const f = fixture()
  useMediaTransport(async () => new Response('failed', { status: 429 }))
  const job = startRebrand(db, f.store.id, user.id, f.source, { method: 'ai', provider: 'openai' })
  await drainRebrands(db); const failed = getRebrand(db, f.store.id, job.id)
  assert.equal(failed.status, 'failed'); assert.match(failed.error, /429/); assert.equal(failed.result_url, '')
  assert.throws(() => applyRebrand(db, f.store.id, user.id, job.id, ''), /completed preview/)
  useMediaTransport(null)
  const cancelled = startRebrand(db, f.store.id, user.id, f.source, { method: 'overlay', logo: f.logo })
  await cancelRebrand(db, f.store.id, user.id, cancelled.id); await drainRebrands(db)
  assert.equal(getRebrand(db, f.store.id, cancelled.id).status, 'cancelled')
  const newer = startRebrand(db, f.store.id, user.id, f.source, { method: 'overlay', logo: f.logo }); await drainRebrands(db)
  const ready = getRebrand(db, f.store.id, newer.id)
  applyRebrand(db, f.store.id, user.id, newer.id, changesToken(rebrandChanges(db, f.store.id, f.source, ready.result_url)))
  db.run('UPDATE products SET hero_image=? WHERE id=?', '/newer-merchant-edit.png', f.product.id)
  assert.throws(() => undoRebrand(db, f.store.id, user.id, newer.id), /edited after/)
  assert.equal(db.one<{ hero_image: string }>('SELECT hero_image FROM products WHERE id=?', f.product.id)!.hero_image, '/newer-merchant-edit.png')
 })
})
