import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,existsSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {chromium} from 'playwright';
const dir=mkdtempSync(join(tmpdir(),'modern-funnelish-'));
Object.assign(process.env,{AMBORAS_DB:join(dir,'test.db'),PORT:'0',AMBORAS_LOG_LEVEL:'error',AMBORAS_STOREFRONT_HOST:'',AMBORAS_PUBLIC_ORIGIN:'',AMBORAS_ADMIN_HOST:'',SEED_EMAIL:'',SEED_PASSWORD:''});
const {getDb}=await import('../src/lib/db.ts');
const {register}=await import('../src/control/auth.ts');
const {importAssetFromUrl}=await import('../src/control/assets.ts');
const {duplicateAsset}=await import('../src/control/duplicate-asset.ts');
const {groupedSource}=await import('./fixtures/grouped-source.ts');
const db=getDb(),owner=register(db,{email:'modern-ui@example.test',password:'modern-fixture-password'});
// Minimal reproduction of the real template's structure and field names, including
// its mislabeled shipping_state field and source-JS-dependent phone widget.
// Fictional test merchandise: no source artwork or merchant content is published.
const field=(name,label,extra='')=>`<div class="element-wrapper"><div class="form-element"><label class="fe-label">${label}</label><input class="fe-input" name="${name}" ${extra}></div></div>`;
const {html:grouped}=groupedSource();
const choices=grouped.match(/<main>([\s\S]*?)<\/main>/)[1].replace('<a href="#submit-step">Continue</a>','').replace(/<label>Delivery ([123])(<input[^>]+>)<\/label>/g,'<div class="product-list"><style>.source-choice{color:black}</style><label>Delivery $1$2</label></div>');
const html=grouped.replace(/<main>[\s\S]*?<\/main>/,`<main class="main-wrapper"><header>Imported fixture brand</header><div class="section_row"><section>${choices}<h2>Contact information</h2>${field('first_name','First name')}${field('last_name','Last name')}${field('email','Email address')}${field('phone','Phone Number*','style="display:none"').replace('</div></div>','<div class="pn__wrapper"><button class="pn-prefix__button">Broken prefix</button><input type="tel"></div></div></div>')}<h2>Delivery address</h2>${field('shipping_state','Street Address')}<div class="element-wrapper"><div class="form-element"><label class="fe-label">Country</label><select name="shipping_country"><option value="US">United States</option></select></div></div>${field('shipping_city','City')}${field('shipping_zip','ZIP')}<h2>Payment method</h2><div class="payment-form"><input type="radio" name="checkout[payment_gateway]" checked><p>Old source cash-on-delivery widget</p></div></section><aside><div class="container"><style>.source-recap{color:red}</style>Delivery 1</div><div class="container" style="display:none">Delivery 2</div><div class="container" style="display:none">Delivery 3</div><div class="order-summary">Stale $999 order</div><a class="source-pay" href="#submit-step">Confirm and checkout</a></aside></div><div class="faq"><div class="faq-header">Delivery FAQ</div><div class="faq-content-wrapper"><p>Fixture delivery answer.</p></div></div><div><video class="__video" preload="none"></video><svg class="play-button"></svg></div></main>`).replace('</head>','<meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;font:16px Arial;background:#ffe6e9}main{max-width:1000px;margin:auto;padding:20px}.section_row{display:grid;grid-template-columns:1fr 1fr;gap:24px}.form-element{margin:10px 0}.fe-label{display:block}.fe-input,select{width:100%;height:44px}label:has(input[type=radio]),label:has(input[type=checkbox]){display:block;padding:14px;background:white;margin:8px 0}.source-pay{display:block;background:#791922;color:white;border-radius:18px;padding:15px}.co-block{display:block!important}.field{float:left;width:100%}@media(max-width:700px){.section_row{grid-template-columns:1fr}}</style></head>');
const imp=await importAssetFromUrl(db,owner.id,{url:'https://fixture.example/checkout',name:'Modern imported checkout fixture',kind:'funnel',scope:'page',fetchImpl:async()=>new Response(html,{headers:{'content-type':'text/html'}})});
const {server}=await import('../src/main.ts');await new Promise(r=>server.listening?r():server.once('listening',r));
const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,...(existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
after(async()=>{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));db.handle.close();rmSync(dir,{recursive:true,force:true});});
for(const width of [1440,390,320]) test(`modern imported checkout has one design and operable source controls at ${width}px`,async()=>{
 const ctx=await browser.newContext({viewport:{width,height:1000}});await ctx.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());await ctx.request.post(origin+'/login',{form:{email:'modern-ui@example.test',password:'modern-fixture-password'}});
 const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=origin+'/preview/'+imp.store.slug;
 await page.goto(base+'/checkout');await page.waitForFunction(()=>window.__COPY_COMMERCE_READY);
 const total=async cents=>{await page.waitForFunction(c=>document.querySelector('[data-pay-total]').textContent.includes((c/100).toFixed(2)),cents);assert.equal((await ctx.request.get(base+'/cart/state').then(r=>r.json())).totals.totalCents,cents);};
 await total(10199);
 assert.equal(await page.locator('#checkout-form').count(),1);assert.equal(await page.locator('#checkout-form').evaluate(n=>n.parentElement.hasAttribute('data-owned-funnelish')),true);
 assert.equal(await page.locator('[data-funnel-selection],[data-funnel-addons],.payment-form,.pn__wrapper,a[href="#submit-step"]').count(),0);
 const geometry=await page.locator('[data-owned-funnelish]').evaluate(n=>({width:n.getBoundingClientRect().width,parent:n.parentElement.getBoundingClientRect().width}));assert.ok(geometry.width>=geometry.parent-2,'payment form must fill its source slot');
 assert.ok(await page.locator('[data-owned-source-address] label').first().evaluate(n=>parseFloat(getComputedStyle(n).fontSize)>=14));
 assert.equal(await page.locator('[data-owned-source-address] .form-element').first().evaluate(n=>n.firstElementChild.tagName),'LABEL');assert.equal(await page.locator('[data-owned-source-address] input').first().evaluate(n=>getComputedStyle(n).borderRadius),await page.locator('[name=postal]').evaluate(n=>getComputedStyle(n).borderRadius));
 assert.equal(await page.locator('#methods').isVisible(),false);assert.equal(await page.locator('[name="checkout[payment_gateway]"]').count(),0);
 for(const name of ['email','firstName','lastName','line1','city','postal','phone','country']){const f=page.locator('[name="'+name+'"]');assert.equal(await f.count(),1,name);assert.equal(await f.isVisible(),true,name);assert.equal(await f.getAttribute('form'),'checkout-form');}
 assert.equal(await page.locator('[name=line1]').getAttribute('data-copy-checkout-field'),'');assert.equal(await page.locator('[name=phone]').getAttribute('type'),'tel');
 // Exercise validation only: all required fields are empty, so no submission
 // can occur. Restore preview protection before filling any field.
 await page.evaluate(()=>{window.__CHECKOUT.preview=false;document.getElementById('checkout-form').requestSubmit();window.__CHECKOUT.preview=true;});
 assert.equal(await page.locator('[name=firstName]').getAttribute('aria-invalid'),'true');assert.ok(await page.locator('.form-element>.field-error').count()>=6);await page.locator('[name=firstName]').fill('Fixture');assert.equal(await page.locator('[name=firstName]').getAttribute('aria-invalid'),null);
 await page.locator('[name=email]').fill('buyer@example.test');await page.locator('[name=firstName]').fill('Fixture');await page.locator('[name=lastName]').fill('Buyer');await page.locator('[name=line1]').fill('123 Test Street');await page.locator('[name=city]').fill('Test City');await page.locator('[name=postal]').fill('10001');await page.locator('[name=phone]').fill('+1 555 0100');
 const draft=await page.locator('#checkout-form').evaluate(n=>Object.fromEntries(new FormData(n)));assert.equal(draft.line1,'123 Test Street');assert.equal(draft.email,'buyer@example.test');
 await page.locator('[data-copy-choice=addon][value="4"]').uncheck();await total(8999);await page.locator('[data-copy-choice=addon][value="5"]').check();await total(9499);await page.locator('[data-copy-choice=primary][value="6"]').check();await total(5799);await page.locator('[data-copy-choice=primary][value="7"]').check();await total(5799);await page.locator('[data-copy-choice=primary][value="8"]').check();await total(9499);
 await page.locator('[data-copy-choice=shipping][value="2"]').check();await total(9200);assert.equal(await page.locator('[data-copy-shipping-preview]:visible').innerText(),'Delivery 2');await page.locator('[data-copy-choice=shipping][value="3"]').check();await total(9699);await page.locator('[data-copy-choice=shipping][value="1"]').check();await total(9499);
 await page.locator('[data-copy-choice=addon][value="4"]').check();await total(10699);await page.locator('[data-copy-choice=addon][value="5"]').uncheck();await total(10199);
 await page.locator('[name=billingSame]').uncheck();assert.equal(await page.locator('.co-billing').isVisible(),true);await page.locator('[name=billingSame]').check();assert.equal(await page.locator('.co-billing').isVisible(),false);
 await page.locator('.faq-header').click();assert.equal(await page.locator('.faq-content-wrapper').isVisible(),true);await page.locator('.faq-header').press('Space');assert.equal(await page.locator('.faq-content-wrapper').isVisible(),false);assert.equal(await page.locator('video').evaluate(n=>n.controls),true);assert.equal(await page.locator('.play-button').isVisible(),false);await page.locator('video').evaluate(n=>n.dispatchEvent(new Event('error')));assert.equal(await page.locator('[data-copy-video-error]').innerText(),'Video unavailable in this imported preview.');
 assert.equal(await page.locator('#pay').isDisabled(),true);assert.equal(await page.locator('#pay').getAttribute('form'),'checkout-form');assert.ok(await page.locator('#pay').evaluate(n=>n.getBoundingClientRect().height>=44));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));assert.deepEqual(errors,[]);
 if(process.env.CHECKOUT_SCREENSHOTS){mkdirSync(process.env.CHECKOUT_SCREENSHOTS,{recursive:true});await page.screenshot({path:join(process.env.CHECKOUT_SCREENSHOTS,`modern-fixture-${width}.png`),fullPage:true});}await ctx.close();
});
test('modern copied checkout remains independently bound after duplication',async()=>{const copy=duplicateAsset(db,owner.id,imp.store.id,{name:'Independent modern checkout'}).store;const ctx=await browser.newContext();await ctx.request.post(origin+'/login',{form:{email:'modern-ui@example.test',password:'modern-fixture-password'}});const p=await ctx.newPage();await p.goto(origin+'/preview/'+copy.slug+'/checkout');await p.waitForFunction(()=>window.__COPY_COMMERCE_READY);assert.equal(await p.locator('#checkout-form').count(),1);assert.equal(await p.locator('[data-funnel-selection]').count(),0);const state=await ctx.request.get(origin+'/preview/'+copy.slug+'/cart/state').then(r=>r.json());assert.equal(state.totals.totalCents,10199);assert.ok(state.items.every(i=>!imp.products.some(p=>p.id===i.productId)));await ctx.close();});
