import { escapeHtml as e } from '../lib/http.ts'
import type { Db } from '../lib/db.ts'
import type { Store } from '../control/stores.ts'
import { listPages } from '../pages/store.ts'
import { listReviews, getReview, reviewRevision, citationLabel } from '../control/cro-review.ts'
import { readCopyReport } from '../pages/clone-report.ts'
import { decodeMediaAttribute } from '../pages/clone-media.ts'
export function croReviewPage(db:Db,store:Store,reviewId='',flash=''):string {
 const pages=listPages(db,store.id),reviews=listReviews(db,store.id),review=reviewId?getReview(db,store.id,reviewId):null
 const stale=review?reviewRevision(db,store.id)!==(review.status==='applied'?review.appliedRevision:review.baseRevision):false
 const remainingStale=review?.status==='applied'&&review.suggestions.some(s=>s.status==='pending')
 const prefix='/admin/cro-review',storeQuery='?storeId='+encodeURIComponent(store.id)
 return `<div class="page-head"><div><h1>Course review</h1><p>Keep the copy faithful. Review ideas, then choose exactly what to change.</p></div><a class="button" href="/preview/${e(store.slug)}" target="_blank" rel="noopener">Preview store</a></div>
 ${flash?`<div class="notice ${flash.startsWith('!')?'bad':''}" role="status">${e(flash.replace(/^!/,''))}</div>`:''}
 <section class="card"><h2>Copy fidelity first</h2><p>Importing and duplicating do not apply course advice. Use the copy report and preview to verify product prices, variants, assets, layout and cart behavior. Source payment sessions and external checkout services cannot be duplicated.</p>
 ${pages.filter(p=>p.sourceUrl).map(p=>{const report=readCopyReport(db,store.id,p.id);return `<p><a href="/admin/pages/${e(p.id)}/copy-report">${e(p.title)} — copy report</a> · ${report?.site?.complete?'Complete for the captured scope':report?'Review captured scope and gaps':'No verified copy report'} · <a href="/preview/${e(store.slug)}${p.isHome?'':'/pages/'+e(p.handle)}" target="_blank" rel="noopener">View copy</a></p>`}).join('')||'<p>No source import report in this store. Review the preview at desktop and mobile widths.</p>'}
 </section><section class="card"><h2>Generate suggestions without changing the store</h2><p>Up to three small text edits, with a course source, a reason and uncertainty. Prices, policies, reviews, guarantees, layouts, assets and checkout are protected. Product claims still need merchant review.</p>
 <form method="post" action="${prefix}/generate${storeQuery}"><label>Page scope<select name="pageId"><option value="">Up to three imported pages and product subtitles</option>${pages.filter(p=>p.mode==='html'&&!['checkout','cart','upsell','downsell','thankyou'].includes(p.role)).map(p=>`<option value="${e(p.id)}">${e(p.title)} and product subtitles</option>`).join('')}</select></label><label>Review focus<input name="focus" maxlength="500" placeholder="Make the message clearer without changing its meaning"></label><button class="button primary" type="submit">Review without changing content</button></form></section>
 ${review?`<section class="card" data-cro-review="${e(review.id)}"><h2>Proposed edits</h2><p>${e(review.model)} · ${e(review.status)} · ${e(review.createdAt)}</p>${stale?'<div class="notice bad" role="alert">This review is stale. The store changed. Generate a new review before accepting edits. Undo is blocked when it would overwrite later work.</div>':''}${remainingStale&&!stale?'<div class="notice" role="alert">Unselected suggestions are stale after this accepted batch. Generate a new review before accepting further edits.</div>':''}${review.error?`<p class="notice bad">Last application failed and rolled back: ${e(review.error)}</p>`:''}
 <form method="post" action="${prefix}/${e(review.id)}/accept${storeQuery}" id="cro-accept"><input type="hidden" name="token" value="${e(review.token)}"><input type="hidden" name="intent" value="accept_selected">
 ${review.suggestions.map(s=>`<article class="card" data-suggestion="${e(s.suggestionId)}"><h3>${e(s.label)}</h3><p>Status: ${e(s.status)}</p><div class="cro-diff"><div><strong>Before</strong><pre>${e(s.text)}</pre></div><div><strong>Proposed after</strong><pre>${e(s.target==='page'?decodeMediaAttribute(s.after):s.after)}</pre></div></div><p><strong>Reason:</strong> ${e(s.reason)}</p><p><strong>Uncertainty:</strong> ${e(s.uncertainty)}</p><details><summary>Course source</summary><p>${e(citationLabel(s))}</p><p>Passage ${e(s.sourceId)}</p><blockquote>${e(s.quote)}</blockquote><p>The proposed edit is advice derived from this source, not a claim of tested conversion lift.</p></details>${s.status==='pending'?`<label><input type="checkbox" name="accept_${e(s.suggestionId)}" ${stale||review.status!=='pending'?'disabled':''}> Accept this exact edit</label><button class="button" type="submit" form="reject-${e(s.suggestionId)}">Reject this suggestion</button>`:''}</article>`).join('')||'<p>No safe, worthwhile text edits were proposed. Your store has not changed.</p>'}
 ${review.status==='pending'&&review.suggestions.some(s=>s.status==='pending')?`<button class="button primary" type="submit" ${stale?'disabled':''}>Apply selected accepted edits</button><p>Unchecked edits are not applied. Applying any selection makes remaining suggestions stale; re-review them against the updated store.</p>`:''}</form>
 ${review.suggestions.filter(s=>s.status==='pending').map(s=>`<form id="reject-${e(s.suggestionId)}" method="post" action="${prefix}/${e(review.id)}/reject${storeQuery}"><input type="hidden" name="token" value="${e(review.token)}"><input type="hidden" name="suggestionId" value="${e(s.suggestionId)}"></form>`).join('')}
 ${review.status==='applied'?`<form method="post" action="${prefix}/${e(review.id)}/undo${storeQuery}"><input type="hidden" name="token" value="${e(review.token)}"><button class="button" type="submit" ${stale?'disabled':''}>Undo this accepted batch</button><p>Restores only the fields in this batch. Later store changes block undo to protect your work.</p></form><p><a href="/preview/${e(store.slug)}" target="_blank" rel="noopener">Check the updated preview</a> and verify desktop, mobile and cart behavior.</p>`:''}
 <ul>${review.limitations.map(x=>`<li>${e(x)}</li>`).join('')}</ul></section>`:''}
 <section class="card"><h2>Review history</h2>${reviews.map(r=>`<p><a href="${prefix}/${e(r.id)}${storeQuery}">${e(r.createdAt)} — ${r.suggestions.length} suggestions</a> · ${e(r.status)}</p>`).join('')||'<p>No reviews yet.</p>'}</section><style>.cro-diff{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.cro-diff pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--raise);padding:12px}#cro-accept input[type=checkbox]{width:auto}@media(max-width:700px){.cro-diff{grid-template-columns:minmax(0,1fr)}}</style>`
}
