(() => {
  let data=JSON.parse(document.getElementById('discount-data').textContent),draft=null,sample=[],timer,request,sequence=0,returnFocus;
  const root=document.querySelector('.discount-studio'),dialog=root.querySelector('dialog'),fields=root.querySelector('[data-discount-fields]'),form=root.querySelector('form'),quote=root.querySelector('[data-discount-quote]'),error=root.querySelector('[data-discount-error]');
  const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=value=>new Intl.NumberFormat(undefined,{style:'currency',currency:data.currency}).format(value/10**data.digits),amount=value=>(value/10**data.digits).toFixed(data.digits),step=data.digits?'0.'+'0'.repeat(data.digits-1)+'1':'1';
  const typeName=id=>data.types.find(type=>type.id===id)?.name||id;
  const product=id=>data.products.find(p=>p.id===id),variants=()=>data.products.flatMap(p=>p.variants.map(v=>({...v,productId:p.id,label:p.title+(v.title&&!/^(default|default title)$/i.test(v.title)?' — '+v.title:'')})));
  const option=(value,label,current)=>`<option value="${e(value)}" ${String(current)===String(value)?'selected':''}>${e(label)}</option>`;
  const input=(name,label,value,attrs='')=>`<label class="field">${e(label)}<input name="${e(name)}" value="${e(value)}" ${attrs}></label>`;
  const select=(name,label,choices,value)=>`<label class="field">${e(label)}<select name="${e(name)}" aria-label="${e(label)}">${choices.map(([v,l])=>option(v,l,value)).join('')}</select></label>`;
  const check=(name,label,value)=>`<label class="discount-check"><input type="checkbox" name="${e(name)}" ${value?'checked':''}>${e(label)}</label>`;
  const section=(title,html)=>`<section class="discount-section"><h3>${e(title)}</h3>${html}</section>`;
  const pairs=items=>items.map(item=>[item.id,item.title||item.label]);
  const priceTotal=(tier,p)=>{const unit=Math.min(...(p?.variants.map(v=>v.priceCents)||[0]));return tier.priceType==='total'?Math.round(Number(tier.value)*10**data.digits):tier.priceType==='each'?Math.round(Number(tier.value)*10**data.digits)*tier.quantity:Math.round(unit*tier.quantity*(1-Number(tier.value)/100))};
  const summary=offer=>{
    if(offer.type==='quantity')return `${product(offer.productId)?.title||'Product'} · ${offer.pricingMode==='multiples'?'Complete packs':'Bulk quantity pricing'} · ${offer.tiers.length} tiers`;
    const scope=offer.scope==='all'?'all eligible items':offer.scope==='products'?`${offer.productIds.length} product${offer.productIds.length===1?'':'s'}`:offer.scope==='variants'?`${offer.variantIds.length} variants`:offer.scope==='selection'?'selected products, variants and collections':`${offer.collectionIds.length} collections`;
    if(offer.type==='amount')return `${offer.amountType==='fixed'?money(Math.round(Number(offer.value)*10**data.digits)):offer.value+'%'} off · ${scope}`;
    if(offer.type==='tiered')return `${offer.tiers.length} quantity thresholds · ${scope}`;
    if(offer.type==='bogo')return `Buy ${offer.buyQuantity}, get ${offer.getQuantity} ${Number(offer.value)===100?'free':offer.value+'% off'}`;
    if(offer.type==='mix_match')return `${offer.value}% off when buying ${offer.requiredDistinctProducts} different products`;
    if(offer.type==='fixed_bundle')return `${offer.setQuantity} items for ${money(Math.round(Number(offer.bundlePrice)*10**data.digits))} · complete sets`;
    return `Free shipping${offer.minSubtotal?' from '+money(Math.round(Number(offer.minSubtotal)*10**data.digits)):''}`;
  };
  function list(){
    const search=root.querySelector('[data-discount-search]').value.toLowerCase(),status=root.querySelector('[data-discount-status]').value;
    const offers=data.offers.filter(o=>(!data.quantityOnly||o.type==='quantity')&&[o.title,product(o.productId)?.title,o.code,typeName(o.type)].join(' ').toLowerCase().includes(search)&&(status==='all'||status==='paused'?status==='all'||['paused','disabled','expired','exhausted'].includes(o.status):o.status===status));
    root.querySelector('[data-discount-list]').innerHTML=offers.length?offers.map(o=>`<article class="discount-offer"><div><h2>${e(o.title)}<span class="discount-state ${e(o.status)}">${e(o.status==='exhausted'?'Use limit reached':o.status==='disabled'?'Inactive':o.status==='paused'?'Inactive':o.status)}</span></h2><p>${e(summary(o))}</p><p>${e(o.type==='quantity'?'Product page offer':o.method==='code'?'Code: '+o.code:'Automatic discount')}</p>${o.type==='quantity'?`<div class="discount-pills">${o.tiers.map(t=>`<span class="discount-pill">${e(t.label||'Buy '+t.quantity)}<b>${money(priceTotal(t,product(o.productId)))}</b>${t.compare&&Number(t.compare)*10**data.digits>priceTotal(t,product(o.productId))?`<s>${money(Math.round(Number(t.compare)*10**data.digits))}</s>`:''}</span>`).join('')}</div>`:''}</div><div class="discount-offer-actions"><button class="btn" type="button" data-discount-edit="${e(o.id)}" aria-label="Edit ${e(o.title)}">Edit</button><button class="btn" type="button" data-discount-toggle="${e(o.id)}" aria-label="${['active','scheduled'].includes(o.status)?'Deactivate':'Activate'} ${e(o.title)}">${['active','scheduled'].includes(o.status)?'Deactivate':'Activate'}</button></div></article>`).join(''):'<div class="discount-empty"><h2>No matching discounts</h2><p class="muted">Create a discount to set up pricing, rewards or shipping offers.</p></div>';
  }
  function defaults(type){return {type,entity:type==='quantity'?'bundle':'promotion',title:type==='quantity'?'Bundle & save':type==='amount'?'New discount':typeName(type),productId:'',pricingMode:'multiples',tiers:[{quantity:1,priceType:'percent',value:'0',label:'Buy 1'},{quantity:2,priceType:'percent',value:'15',label:'Buy 2',badge:'Most popular'},{quantity:3,priceType:'percent',value:'25',label:'Buy 3',badge:'Best value'}],layout:'stacked',accent:'',showCompare:true,showPerUnit:true,method:'automatic',code:'',amountType:'percentage',value:type==='bogo'?'100':'10',scope:'all',productIds:[],variantIds:[],collectionIds:[],buyProductIds:[],getProductIds:[],rewardScope:'same',buyQuantity:1,getQuantity:1,requiredDistinctProducts:2,setQuantity:2,bundlePrice:'',minSubtotal:'',minQuantity:'',maxUses:'',priority:0,combinable:false,firstOrderOnly:false,regionScope:'all',regionIds:[],startsAt:'',endsAt:''};}
  function picker(name,label,items,selected=[]){return `<div><label class="field">${e(label)}<input type="search" data-pick-search="${e(name)}" placeholder="Search ${e(label.toLowerCase())}" aria-label="Search ${e(label.toLowerCase())}"></label><div class="discount-pick-list" data-pick-list="${e(name)}">${items.map(item=>`<label class="discount-check" data-pick-label="${e((item.title||item.label).toLowerCase())}"><input type="checkbox" data-pick="${e(name)}" value="${e(item.id)}" ${selected.includes(item.id)?'checked':''}>${e(item.title||item.label)}</label>`).join('')||'<p class="discount-note">No items available.</p>'}</div></div>`;}
  function scope(){return select('scope','Applies to',[['all','All products'],['products','Specific products'],['variants','Specific variants'],['collections','Specific collections'],['selection','Products, variants & collections']],draft.scope)+(draft.scope==='selection'?picker('productIds','Eligible products',data.products,draft.productIds)+picker('variantIds','Eligible variants',variants(),draft.variantIds)+picker('collectionIds','Eligible collections',data.collections,draft.collectionIds):draft.scope==='products'?picker('productIds','Eligible products',data.products,draft.productIds):draft.scope==='variants'?picker('variantIds','Eligible variants',variants(),draft.variantIds):draft.scope==='collections'?picker('collectionIds','Eligible collections',data.collections,draft.collectionIds):'');}
  function tierFields(){return `<p class="muted">${draft.type==='quantity'?(draft.pricingMode==='multiples'?'Each complete pack gets its price. Remaining units keep their normal price; the best fitting pack combination is used.':'The highest quantity threshold applies to every eligible unit.'): 'The highest quantity threshold applies across eligible items.'}</p><div data-discount-tiers>${draft.tiers.map((tier,i)=>`<div class="discount-tier"><div class="discount-tier-head"><h4>${draft.pricingMode==='multiples'&&draft.type==='quantity'?'Pack':'Tier'} ${i+1}</h4><button type="button" data-tier-remove="${i}" aria-label="Remove tier ${i+1}" ${draft.tiers.length===1?'disabled':''}>Remove</button></div><div class="discount-tier-price">${input('tier.'+i+'.quantity',draft.pricingMode==='multiples'&&draft.type==='quantity'?'Items':'From qty',tier.quantity,'type="number" min="1" max="999" step="1" required')}${select('tier.'+i+'.priceType','Price type',[['percent','Percentage off'],['total','Total price'],['each','Price per item']],tier.priceType)}${input('tier.'+i+'.value',tier.priceType==='percent'?'Discount (%)':'Price ('+data.currency+')',tier.value,`type="number" min="0" ${tier.priceType==='percent'?'max="100" step="0.01"':`step="${step}"`} required`)}</div>${draft.type==='quantity'?`<details><summary>Labels, original price & perks${tier.compare?' · '+money(Math.round(Number(tier.compare)*10**data.digits))+' original':''}${tier.freeShipping?' · Free shipping':''}${tier.giftVariantId?' · Gift':''}</summary><div class="discount-fields-row">${input('tier.'+i+'.label','Customer label',tier.label||'','maxlength="150"')}${input('tier.'+i+'.badge','Badge (optional)',tier.badge||'','placeholder="Most popular" maxlength="60"')}</div>${input('tier.'+i+'.compare','Original total ('+data.currency+', optional)',tier.compare||'',`type="number" min="0" step="${step}"`)}${check('tier.'+i+'.freeShipping','Free shipping from this quantity',tier.freeShipping)}${select('tier.'+i+'.giftVariantId','Gift for this tier (one per order)',[['','No gift'],...variants().map(v=>[v.id,v.label])],tier.giftVariantId||'')}${input('tier.'+i+'.giftLabel','Gift label (optional)',tier.giftLabel||'','placeholder="Free travel case"')}</details>`:''}</div>`).join('')}</div><button type="button" class="btn" data-tier-add ${draft.tiers.length>=20?'disabled':''}>Add tier</button>`;}
  const localDate=value=>{if(!value)return '';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)};
  function render(){
    const focused=fields.contains(document.activeElement)?document.activeElement.name:null;
    const quantity=draft.type==='quantity';
    let html=draft.id?'':section('Discount type',`<div class="discount-type-grid">${data.types.map(type=>`<button class="discount-type" type="button" data-discount-type="${type.id}" aria-pressed="${draft.type===type.id}"><b>${e(type.name)}</b><span>${e(type.description)}</span></button>`).join('')}</div>`);
    html+=section('Details',input('title',quantity?'Offer title':'Discount name',draft.title,'required maxlength="150"')+(quantity?select('productId','Product',[['','Choose a product'],...pairs(data.products)],draft.productId)+select('pricingMode','How quantity pricing works',[['multiples','Complete multipacks'],['bulk','Bulk price from a quantity']],draft.pricingMode):select('method','Discount method',[['automatic','Automatic — no code needed'],['code','Discount code']],draft.method)+(draft.method==='code'?input('code','Discount code',draft.code,'placeholder="WELCOME10" required maxlength="40"'):'')));
    if(quantity)html+=section('Pricing & perks',tierFields())+section('Product page appearance',`<div class="discount-fields-row">${select('layout','Layout',[['stacked','Stacked cards'],['row','Side by side']],draft.layout)}${input('accent','Accent color (optional)',draft.accent,'placeholder="#318037" maxlength="7"')}</div>${check('showCompare','Show original prices',draft.showCompare)}${check('showPerUnit','Show price per item',draft.showPerUnit)}`);
    else {
      let benefits='';
      if(draft.type==='amount')benefits=`<div class="discount-fields-row">${select('amountType','Discount value',[['percentage','Percentage off'],['fixed','Amount off']],draft.amountType)}${input('value',draft.amountType==='fixed'?'Amount ('+data.currency+')':'Discount (%)',draft.value,`type="number" min="0" step="${draft.amountType==='fixed'?step:'0.01'}" required`)}</div>`;
      if(draft.type==='bogo')benefits=`<div class="discount-fields-row">${input('buyQuantity','Customer buys',draft.buyQuantity,'type="number" min="1" max="999" required')}${input('getQuantity','Customer gets',draft.getQuantity,'type="number" min="1" max="999" required')}</div>${input('value','Reward discount (%)',draft.value,'type="number" min="1" max="100" step="0.01" required')}<p class="discount-note">Use 100% for a free reward. The reward items must be in the cart; the cheapest qualifying rewards are discounted.</p>${select('rewardScope','Reward products',[['same','Same eligible products'],['different','Different products']],draft.rewardScope)}`;
      if(draft.type==='mix_match')benefits=`<div class="discount-fields-row">${input('requiredDistinctProducts','Different products required',draft.requiredDistinctProducts,'type="number" min="2" max="50" required')}${input('value','Discount (%)',draft.value,'type="number" min="1" max="100" step="0.01" required')}</div><p class="discount-note">Once this many different products qualify, the discount applies to all eligible items.</p>`;
      if(draft.type==='fixed_bundle')benefits=`<div class="discount-fields-row">${input('setQuantity','Items per set',draft.setQuantity,'type="number" min="1" max="999" required')}${input('bundlePrice','Price for the complete set ('+data.currency+')',draft.bundlePrice,`type="number" min="${step}" step="${step}" required`)}</div><p class="discount-note">Each complete set gets this price. Extra items keep their regular price.</p>`;
      if(draft.type==='tiered')benefits=tierFields();
      if(draft.type==='free_shipping')benefits='<p class="muted">Waive delivery charges when the requirements below are met.</p>';
      html+=section('Discount value',benefits);
      html+=section('Eligible items',draft.type==='bogo'&&draft.rewardScope==='different'?picker('buyProductIds','Buy products',data.products,draft.buyProductIds)+picker('getProductIds','Reward products',data.products,draft.getProductIds):scope());
      html+=section('Requirements',`<div class="discount-fields-row">${input('minSubtotal','Minimum order spend ('+data.currency+', optional)',draft.minSubtotal,`type="number" min="0" step="${step}"`)}${draft.type==='fixed_bundle'?'':input('minQuantity','Minimum eligible quantity (optional)',draft.minQuantity,'type="number" min="1" max="999"')}</div>${check('firstOrderOnly','First order only',draft.firstOrderOnly)}${select('regionScope','Markets',[['all','All markets'],['selected','Selected markets']],draft.regionScope)}${draft.regionScope==='selected'?picker('regionIds','Eligible markets',data.regions,draft.regionIds):''}${input('maxUses','Total use limit (optional)',draft.maxUses,'type="number" min="1" max="1000000"')}`);
      html+=section('Schedule & combinations',`<div class="discount-fields-row">${input('startsAt','Starts at (optional)',localDate(draft.startsAt),'type="datetime-local"')}${input('endsAt','Ends at (optional)',localDate(draft.endsAt),'type="datetime-local"')}</div><p class="discount-note">Dates use your local time zone. Leave the start blank to begin immediately.</p>${check('combinable','Can combine with other discounts',draft.combinable)}<p class="discount-note">When off, this discount applies by itself and takes priority over combinable offers.</p><details><summary>Priority when offers overlap</summary>${input('priority','Priority (higher wins)',draft.priority,'type="number" min="0" max="100"')}</details>`);
    }
    fields.innerHTML=html;root.querySelector('#discount-dialog-title').textContent=draft.id?(quantity?'Edit product offer':'Edit discount'):'Create discount';renderSample();preview();if(focused)fields.querySelector(`[name="${CSS.escape(focused)}"]`)?.focus({preventScroll:true});
  }
  function renderSample(){root.querySelector('[data-discount-sample]').innerHTML=sample.map((item,i)=>`<div class="discount-sample-item">${select('sample.'+i+'.variantId','Test item '+(i+1),variants().map(v=>[v.id,v.label+' · '+money(v.priceCents)]),item.variantId)}<div class="discount-fields-row">${input('sample.'+i+'.quantity','Quantity',item.quantity,'type="number" min="1" max="999"')}<button type="button" class="btn" data-sample-remove="${i}" aria-label="Remove test item ${i+1}">Remove</button></div></div>`).join('');}
  function open(offer){returnFocus=document.activeElement;draft=offer?structuredClone(offer):defaults(data.quantityOnly?'quantity':'amount');const first=product(draft.productId)||data.products.find(p=>draft.productIds?.includes(p.id))||data.products[0];sample=first?.variants[0]?[{variantId:first.variants[0].id,quantity:2}]:[];error.textContent='';render();dialog.showModal();}
  function close(){clearTimeout(timer);request?.abort();sequence++;dialog.close();draft=null;returnFocus?.focus();}
  async function api(path,body,signal){const response=await fetch(path+'?storeId='+encodeURIComponent(data.storeId),{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(body),signal});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save the discount');return result;}
  function preview(){clearTimeout(timer);request?.abort();const current=++sequence;timer=setTimeout(async()=>{request=new AbortController();quote.setAttribute('aria-busy','true');try{const result=await api('/admin/discounts/preview',{...draft,sample},request.signal);if(current!==sequence)return;quote.innerHTML=`<div class="discount-quote"><div><span>Subtotal</span><span>${money(result.subtotalCents)}</span></div><div class="discount-saving"><span>Discount</span><span>−${money(result.discountCents)}</span></div><div class="discount-total"><span>Items total</span><span>${money(result.totalCents)}</span></div>${result.freeShipping?'<div class="discount-saving"><span>Delivery</span><span>Free shipping</span></div>':''}${result.gift?`<div class="discount-saving"><span>Included gift</span><span>${e(result.gift)}</span></div>`:''}${!result.qualifies?'<p class="discount-preview-warning">This test cart does not qualify yet.</p>':''}</div>`;}catch(failure){if(failure.name!=='AbortError'&&current===sequence)quote.innerHTML=`<p class="discount-preview-warning">${e(failure.message)}</p>`;}finally{if(current===sequence)quote.removeAttribute('aria-busy')}},250);}
  function update(control){
    if(!draft)return;
    if(control.dataset.pick){const name=control.dataset.pick;draft[name]=[...fields.querySelectorAll(`[data-pick="${name}"]:checked`)].map(input=>input.value);preview();return;}
    const name=control.name;if(!name)return;let value=control.type==='checkbox'?control.checked:control.value;
    if(name.startsWith('tier.')){const [,index,key]=name.split('.');draft.tiers[index][key]=key==='quantity'?Number(value):value;if(key==='priceType'){render();return}}
    else if(name.startsWith('sample.')){const [,index,key]=name.split('.');sample[index][key]=key==='quantity'?Number(value):value;}
    else {draft[name]=value;if(['productId','scope','amountType','method','rewardScope','pricingMode','regionScope'].includes(name)){if(name==='productId'){const p=product(value);if(p?.variants[0])sample=[{variantId:p.variants[0].id,quantity:2}]}render();return}}
    preview();
  }
  root.addEventListener('input',event=>{const c=event.target;if(c.matches('[data-discount-search]'))return list();if(c.dataset.pickSearch){const list=fields.querySelector(`[data-pick-list="${c.dataset.pickSearch}"]`);list.querySelectorAll('[data-pick-label]').forEach(row=>row.hidden=!row.dataset.pickLabel.includes(c.value.toLowerCase()));return}if(c.matches('input:not([type=checkbox])'))update(c)});
  root.addEventListener('change',event=>{if(event.target.matches('[data-discount-status]'))list();else if(event.target.matches('select,input[type=checkbox]'))update(event.target)});
  root.addEventListener('click',async event=>{
    const button=event.target.closest('button');if(!button)return;
    if(button.hasAttribute('data-discount-create'))return open();
    if(button.dataset.discountEdit)return open(data.offers.find(o=>o.id===button.dataset.discountEdit));
    if(button.hasAttribute('data-discount-close')||button.hasAttribute('data-discount-cancel'))return close();
    if(button.dataset.discountType){draft=defaults(button.dataset.discountType);error.textContent='';return render()}
    if(button.hasAttribute('data-tier-add')){draft.tiers.push({quantity:Math.max(...draft.tiers.map(t=>Number(t.quantity)||0))+1,priceType:'percent',value:'0',label:''});return render()}
    if(button.dataset.tierRemove!==undefined){draft.tiers.splice(Number(button.dataset.tierRemove),1);return render()}
    if(button.hasAttribute('data-sample-add')){if(sample.length>=10||!variants().length)return;sample.push({variantId:variants()[0].id,quantity:1});renderSample();return preview()}
    if(button.dataset.sampleRemove!==undefined){sample.splice(Number(button.dataset.sampleRemove),1);renderSample();return preview()}
    if(button.dataset.discountToggle){const offer=data.offers.find(o=>o.id===button.dataset.discountToggle);button.disabled=true;try{const result=await api('/admin/discounts/status',{id:offer.id,entity:offer.entity,active:!['active','scheduled'].includes(offer.status)});data={...data,...result};list();root.querySelector('[data-discount-list-status]').textContent='Discount status updated.'}catch(failure){root.querySelector('[data-discount-list-status]').textContent=failure.message;button.disabled=false}}
  });
  dialog.addEventListener('cancel',event=>{event.preventDefault();close()});
  form.addEventListener('submit',async event=>{event.preventDefault();const save=root.querySelector('[data-discount-save]');save.disabled=true;error.textContent='';try{const result=await api('/admin/discounts/save',draft);data={...data,...result};close();list();root.querySelector('[data-discount-list-status]').textContent='Discount saved. Product offers and cart pricing are updated.'}catch(failure){error.textContent=failure.message;}finally{save.disabled=false}});
  list();
})();
