import { readFileSync } from 'node:fs'
import type { Db } from '../lib/db.ts'
import type { Store } from '../control/stores.ts'
import { discountData } from '../control/discounts.ts'
const css=readFileSync(new URL('./discounts.css',import.meta.url),'utf8')
const js=readFileSync(new URL('./discounts.js',import.meta.url),'utf8')
export function discountPage(db:Db,store:Store,quantityOnly=false){
  const data={...discountData(db,store),quantityOnly}
  return `<style>${css}</style><section class="discount-studio" aria-label="Discounts"><div class="head"><div><h1>${quantityOnly?'Product offers':'Discounts'}</h1><p class="muted">${quantityOnly?'Multipacks and quantity pricing on your product pages.':'Codes, automatic savings and product offers, in one place.'}</p></div><button type="button" class="btn primary" data-discount-create>Create ${quantityOnly?'product offer':'discount'}</button></div>
  <div class="discount-toolbar"><label>Search <input type="search" data-discount-search placeholder="Search discounts"></label><label>Status <select data-discount-status><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Inactive</option><option value="scheduled">Scheduled</option></select></label>${quantityOnly?'<a href="/admin/promotions">View all discounts →</a>':''}</div><div data-discount-list></div><p role="status" data-discount-list-status></p>
  <dialog class="discount-dialog" aria-labelledby="discount-dialog-title"><div class="discount-dialog-head"><div><p class="discount-eyebrow">Discount builder</p><h2 id="discount-dialog-title">Create discount</h2></div><button type="button" class="btn" data-discount-close aria-label="Close discount builder">✕</button></div><form data-discount-form novalidate><div class="discount-dialog-body"><div data-discount-fields></div><aside class="discount-preview" aria-label="Discount preview"><h3>Test this offer</h3><p class="muted">Try a cart and see the price customers would pay.</p><div data-discount-sample></div><button type="button" class="btn" data-sample-add>Add test item</button><div data-discount-quote aria-live="polite"></div><p class="discount-note">Shows this offer on its own. Preview assumes it is active and any customer or market requirements are met. Tax and delivery rates are added at checkout.</p></aside></div><div class="discount-dialog-foot"><p role="alert" data-discount-error></p><button type="button" class="btn" data-discount-cancel>Cancel</button><button class="btn primary" type="submit" data-discount-save>Save discount</button></div></form></dialog>
  <noscript><p>Enable JavaScript to use the visual discount builder.</p></noscript></section><script type="application/json" id="discount-data">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script>${js}</script>`
}
