import { id } from '../lib/ids.ts'
import { escapeHtml as e } from '../lib/http.ts'
import { json, type Db } from '../lib/db.ts'
import type { Store } from '../control/stores.ts'
import { listStoreMedia } from '../control/media.ts'
import { changesToken, listRebrands, rebrandChanges, rebrandDefaults, type RebrandJob } from '../control/media-rebrand.ts'
import { mediaEditingAvailability, type RebrandSpec } from '../control/media-render.ts'

export const mediaRebrandStyle = `<style>.rebrand [hidden]{display:none!important}.rebrand .field{min-width:0}.rebrand .field input,.rebrand .field select,.rebrand .field textarea{width:100%;min-width:0}.rebrand-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:20px}.rebrand-preview{width:100%;height:340px;object-fit:contain;background:repeating-conic-gradient(#f5f5f5 0% 25%,#fff 0% 50%) 50%/20px 20px;border:1px solid var(--line);border-radius:10px}.rebrand figure{margin:0;min-width:0}.rebrand figure figcaption{margin:8px 0 14px;font-weight:600}.rebrand .row{flex-wrap:wrap}.rebrand-status{padding:16px;background:#f0f5ff;border-radius:10px;margin:16px 0}.rebrand-history{display:grid;gap:8px;margin-top:20px}.rebrand-history a{display:flex;justify-content:space-between;gap:16px;padding:12px;border:1px solid var(--line);border-radius:8px;overflow-wrap:anywhere}.media-card video{width:100%;height:190px;object-fit:contain;background:#f6f6f6}.media-card figcaption{flex-wrap:wrap;gap:8px}.media-card figcaption>div{min-width:0}.media-card .media-actions{display:flex;gap:6px;flex-wrap:wrap}.rebrand .logo-preview{max-width:170px;max-height:80px;object-fit:contain;margin:8px 0}.rebrand .form-note{font-size:12px;color:var(--muted);margin:6px 0 12px}.rebrand .error{background:#fff0ee;color:#a3231a;padding:12px;border-radius:8px}.rebrand-usage{font-size:13px;margin:12px 0;line-height:1.7}@media(max-width:720px){.rebrand-grid{grid-template-columns:minmax(0,1fr)}.rebrand-preview{height:260px}.rebrand-history a{flex-direction:column;gap:4px}}</style>`
const preview = (url: string, kind: string, label: string) => kind === 'video' ? `<video class="rebrand-preview" src="${e(url)}" controls playsinline preload="metadata" aria-label="${e(label)}"></video>` : `<img class="rebrand-preview" src="${e(url)}" alt="${e(label)}">`
const query = (storeId: string) => `storeId=${encodeURIComponent(storeId)}`
export function rebrandHistory(db: Db, store: Store): string {
  const jobs = listRebrands(db, store.id)
  return jobs.length ? `<section class="rebrand rebrand-history" aria-label="Recent media edits"><h2>Recent media edits</h2>${jobs.slice(0, 12).map(job => `<a href="/admin/media/rebrand/${job.id}?${query(store.id)}"><span>${e(json<RebrandSpec>(job.spec, {} as RebrandSpec).brandName)} · ${job.kind}</span><span>${e(job.phase)} · ${e(job.created_at.slice(0, 16).replace('T', ' '))}</span></a>`).join('')}</section>` : ''
}
export function rebrandForm(db: Db, store: Store, source: string, previous?: RebrandJob): string {
  const media = listStoreMedia(db, store.id).find(item => item.url === source)
  if (!media || media.kind === 'embed') return '<div class="card"><h1>Choose media to rebrand</h1><p>Open a direct image or video file from this asset’s library. For an embedded player, add the original video file first.</p><a class="btn" href="/admin/media">Back to Media</a></div>'
  const available = mediaEditingAvailability(), saved = previous ? json<RebrandSpec>(previous.spec, rebrandDefaults(db, store.id)) : rebrandDefaults(db, store.id)
  const ai = available.images.some(m => m.available) && (media.kind !== 'video' || available.video)
  const spec = { ...saved, method: ai ? saved.method : 'overlay' }
  const images = listStoreMedia(db, store.id).filter(item => item.kind === 'image')
  const logoPreview = spec.logo && !spec.logo.trim().startsWith('<') ? `<img class="logo-preview" id="logo-preview" src="${e(spec.logo)}" alt="Selected brand logo">` : '<img class="logo-preview" id="logo-preview" alt="Selected brand logo" hidden>'
  return `${mediaRebrandStyle}<div class="rebrand"><div class="head"><div><a href="/admin/media?${query(store.id)}">← Media</a><h1 class="serif">Rebrand ${media.kind}</h1><p class="muted">${e(store.name)} · Create a new version, review it, then choose whether to apply it.</p></div></div><div class="rebrand-grid"><section><figure>${preview(source, media.kind, 'Original ' + media.kind)}<figcaption>Original · ${e(media.label)}</figcaption></figure><p class="form-note">${media.kind === 'video' ? 'AI replacement edits complete 2–30 second clips, up to 1080p, and keeps the original audio. Logo overlays support videos up to 5 minutes and 100MB.' : 'AI replacement changes branding inside the image. Logo overlay adds your exact logo at the chosen position. Animated images become a still image.'}</p></section>
  <form method="post" action="/admin/media/rebrand?${query(store.id)}" enctype="multipart/form-data" class="card" id="rebrand-form"><input type="hidden" name="requestKey" value="${id('edit')}"><input type="hidden" name="source" value="${e(source)}">
  <div class="field"><label for="brand-name">Desired brand name</label><input id="brand-name" name="brandName" required maxlength="100" value="${e(spec.brandName)}"></div>
  <div class="field"><label for="brand-logo">Desired logo</label><select id="brand-logo" name="logo"><option value="">Use brand name only</option>${spec.logo && !images.some(m => m.url === spec.logo) ? `<option value="${e(spec.logo)}" selected>Current brand logo</option>` : ''}${images.map(item => `<option value="${e(item.url)}" ${item.url === spec.logo ? 'selected' : ''}>${e(item.label)} · ${e(item.url.split('/').at(-1)?.slice(0, 38) || '')}</option>`).join('')}</select>${logoPreview}</div>
  <div class="field"><label for="logo-file">Or upload a new logo</label><input id="logo-file" type="file" name="logoFile" accept="image/png,image/jpeg,image/webp,image/svg+xml"><p class="form-note">A transparent PNG works best. This upload overrides the selected logo. Brand choices are remembered for this asset.</p></div>
  <div class="field"><label for="rebrand-method">How to redo it</label><select id="rebrand-method" name="method"><option value="ai" ${spec.method === 'ai' ? 'selected' : ''} ${ai ? '' : 'disabled'}>AI brand replacement${ai ? '' : ' — provider setup needed'}</option><option value="overlay" ${spec.method === 'overlay' ? 'selected' : ''}>Exact logo overlay</option></select></div>
  <div data-method="ai"><div class="field"><label for="image-provider">Image editor${media.kind === 'video' ? ' for the reference frame' : ''}</label><select id="image-provider" name="provider">${available.images.map(m => `<option value="${m.id}" ${m.id === spec.provider ? 'selected' : ''} ${m.available ? '' : 'disabled'}>${e(m.name)}${m.available ? '' : ' — not connected'}</option>`).join('')}</select></div><div class="field"><label for="old-brand">Brand to replace (optional)</label><input id="old-brand" name="oldBrand" maxlength="100" value="${e(spec.oldBrand)}" placeholder="The name currently on the packaging"></div>${media.kind === 'video' ? `<div class="field"><label for="reference-frame">Branding reference time (seconds)</label><input id="reference-frame" name="frame" type="number" min="0" max="29.9" step="0.1" value="${spec.frame}"><p class="form-note">Play the original and choose a moment where the product or branding is clear.</p></div>` : ''}<div class="field"><label for="rebrand-direction">What should change? (optional)</label><textarea id="rebrand-direction" name="direction" rows="3" maxlength="1500" placeholder="Replace the logo on the bottle and end card. Keep the colors and scene.">${e(spec.direction)}</textarea></div><p class="form-note">Generates a new version using your connected providers. Provider charges apply. Check lettering and product details in the preview.</p></div>
  <div data-method="overlay"><div class="field"><label for="logo-position">Logo position</label><select id="logo-position" name="position">${['top-left', 'top-right', 'bottom-left', 'bottom-right'].map(p => `<option value="${p}" ${p === spec.position ? 'selected' : ''}>${p.replace('-', ' ')}</option>`).join('')}</select></div><div class="field"><label for="logo-width">Logo width (% of image or video)</label><input id="logo-width" name="width" type="number" min="5" max="40" value="${spec.width}"></div><p class="form-note">Places your logo over the existing media. Other branding remains unless the overlay covers it. No AI provider needed.</p></div>
  ${!ai ? `<details><summary>Enable AI replacement</summary><p class="form-note">Configure <code>OPENAI_API_KEY</code> or <code>GEMINI_API_KEY</code> on the server${media.kind === 'video' ? ', plus <code>RUNWAYML_API_SECRET</code> for video editing' : ''}, then restart Storemill.</p></details>` : ''}
  ${!available.rendering ? '<p class="error">Install FFmpeg and FFprobe on the server to enable media editing.</p>' : ''}<p id="rebrand-error" role="alert" class="error" hidden></p><button class="btn primary" id="rebrand-submit" type="submit" ${available.rendering ? '' : 'disabled'}>Create preview</button><p class="form-note" id="rebrand-starting" role="status" hidden>Starting your edit…</p></form></div>${rebrandHistory(db, store)}</div>
  <script>(()=>{const form=document.getElementById('rebrand-form'),method=document.getElementById('rebrand-method'),logo=document.getElementById('brand-logo'),file=document.getElementById('logo-file'),image=document.getElementById('logo-preview'),error=document.getElementById('rebrand-error'),button=document.getElementById('rebrand-submit');let objectUrl;
  const toggle=()=>document.querySelectorAll('[data-method]').forEach(section=>{section.hidden=section.dataset.method!==method.value;section.querySelectorAll('input,select,textarea').forEach(control=>control.disabled=section.hidden)});method.addEventListener('change',toggle);toggle();
  const logoChanged=()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);const selected=file.files[0];const url=selected?(objectUrl=URL.createObjectURL(selected)):logo.value;image.hidden=!url||url.trim().startsWith('<');if(!image.hidden)image.src=url};logo.addEventListener('change',logoChanged);file.addEventListener('change',logoChanged);
  form.addEventListener('submit',async event=>{event.preventDefault();if(button.disabled)return;error.hidden=true;if(method.value==='overlay'&&!logo.value&&!file.files.length){error.textContent='Choose or upload a logo for the overlay.';error.hidden=false;logo.focus();return}button.disabled=true;form.setAttribute('aria-busy','true');document.getElementById('rebrand-starting').hidden=false;try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'},signal:AbortSignal.timeout(30000)});if(response.redirected)throw new Error('Your session changed. Reload this page and sign in again.');const data=await response.json();if(!response.ok||!data.url)throw new Error(data.error||'Could not start the edit. Try again.');location.assign(data.url)}catch(reason){error.textContent=reason.message||'Could not reach the server. Try again.';error.hidden=false;button.disabled=false;form.setAttribute('aria-busy','false');document.getElementById('rebrand-starting').hidden=true}})})();</script>`
}
export function rebrandReview(db: Db, store: Store, job: RebrandJob, flash = ''): string {
  const spec = json<RebrandSpec>(job.spec, {} as RebrandSpec), working = ['queued', 'working'].includes(job.status), changes = job.result_url ? rebrandChanges(db, store.id, job.source_url, job.result_url) : []
  const base = `/admin/media/rebrand/${job.id}`, suffix = '?' + query(store.id)
  const counts = Object.entries(changes.reduce((all, c) => { all[c.table] = (all[c.table] || 0) + 1; return all }, {} as Record<string, number>)).map(([table, n]) => { const label = ({ pages: 'page', products: 'product', variants: 'variant', collections: 'collection', custom_blocks: 'custom block', stores: 'brand kit', store_environments: 'draft theme', creative_queue: 'creative' } as Record<string, string>)[table] || 'record'; return `${n} ${label}${n === 1 ? '' : 's'}` }).join(', ')
  return `${mediaRebrandStyle}<div class="rebrand"><div class="head"><div><a href="/admin/media?${query(store.id)}">← Media</a><h1 class="serif">${e(spec.brandName)} · ${job.kind} preview</h1><p class="muted">${e(store.name)} · ${spec.method === 'ai' ? 'AI brand replacement' : 'Exact logo overlay'}</p></div></div>${flash ? `<p class="${flash.startsWith('!') ? 'error' : 'rebrand-status'}" role="status">${e(flash.replace(/^!/, ''))}</p>` : ''}
  <div class="rebrand-status" role="status" aria-live="polite"><strong id="job-phase">${e(job.phase)}</strong>${working ? '<progress aria-label="Media edit in progress" style="display:block;width:100%;margin:12px 0"></progress><p>Your edit continues if you leave this page. Return through Media → Recent media edits.</p><p id="poll-note" class="muted"></p>' : ''}</div>${job.error ? `<p class="error" role="alert">${e(job.error)}</p>` : ''}
  <div class="rebrand-grid"><figure>${preview(job.original_url || job.source_url, job.kind, 'Original ' + job.kind)}<figcaption>Original</figcaption></figure><figure>${job.result_url ? preview(job.result_url, job.kind, 'Rebranded ' + job.kind) : '<div class="rebrand-preview" style="display:grid;place-items:center;color:var(--muted)">Your new version will appear here</div>'}<figcaption>New version</figcaption></figure></div>
  ${job.status === 'review' ? `<div class="card"><h2>Use this version</h2><p class="rebrand-usage">${changes.length ? `Updates ${e(counts)} in <strong>${e(store.name)}</strong>. Responsive versions of the same image are included. ${store.status === 'live' ? 'Published pages and products using this media update immediately. Theme changes stay in draft.' : 'This applies only to the selected asset.'}` : 'The new version is saved in your library. This original is not currently used in editable content; copy the new URL to place it.'}</p><div class="row">${changes.length ? `<form method="post" action="${base}/apply${suffix}"><input type="hidden" name="token" value="${changesToken(changes)}"><button class="btn primary" type="submit">Apply to this asset</button></form>` : ''}<a class="btn" href="${e(job.result_url)}" download>Download new version</a><button class="btn" data-copy="${e(job.result_url)}">Copy new URL</button></div></div>` : ''}
  <div class="row" style="margin-top:16px">${working ? `<form method="post" action="${base}/cancel${suffix}"><button class="btn" type="submit">Cancel edit</button></form>` : `<a class="btn" href="/admin/media/rebrand?${query(store.id)}&source=${encodeURIComponent(job.source_url)}&again=${job.id}">Redo with different branding</a>`}${job.status === 'applied' ? `<form method="post" action="${base}/undo${suffix}"><button class="btn" type="submit">Undo replacement</button></form><a class="btn" href="/preview/${e(store.slug)}" target="_blank" rel="noopener">View asset</a>` : ''}</div></div>
  <script>(()=>{document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copied'}catch{b.textContent='Use Download new version'}});${working ? `let stopped=false;async function poll(){if(stopped)return;try{const r=await fetch(${JSON.stringify(base + '/status' + suffix)},{headers:{Accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(15000)});if(r.redirected||!r.ok)throw new Error();const data=await r.json();document.getElementById('job-phase').textContent=data.phase;document.getElementById('poll-note').textContent='';if(!['queued','working'].includes(data.status)){stopped=true;location.reload();return}}catch{document.getElementById('poll-note').textContent='Connection interrupted. Reconnecting… Your original is safe.'}setTimeout(poll,3000)}setTimeout(poll,1500);addEventListener('pagehide',()=>stopped=true);` : ''}})();</script>`
}
