import { readFileSync } from 'node:fs'
import { escapeHtml as e } from '../lib/http.ts'
import type { Store, StoreEnvironment } from '../control/stores.ts'
import type { Page } from '../pages/store.ts'
import { fontFamiliesFromClone, fontFamilyName } from '../control/assets.ts'
import { sourceThemeFromHtml, sourceThemeScript, fontFacesFromHtml } from '../pages/source-theme.ts'
import { fontLink } from '../storefront/theme.ts'

export function themeEditorPage(input: {store:Store;draft:StoreEnvironment;live:StoreEnvironment;pages:Page[];storeUrl:string}): string {
  const {store,draft,live,pages}=input, home=pages.find(p=>p.isHome)||pages[0], imported=pages.filter(p=>p.mode==='html');
  const saved=Object.keys(draft.brand).length?draft.brand:store.brand;
  const source=Object.keys(saved.sourceTheme||{}).length?saved.sourceTheme!:sourceThemeFromHtml(home?.rawHtml||'');
  const brand=saved.themeCustomized?saved:{...saved,...source};
  const chosenFont=(value:string|undefined,fallback:string)=>value?.split(',')[0]?.trim().replace(/^["']|["']$/g,'')||fallback;
  const families=[...new Set([...imported.flatMap(p=>fontFamiliesFromClone(p.rawHtml)),...(brand.fonts||[]),chosenFont(brand.displayFont,'Playfair Display'),chosenFont(brand.bodyFont,'Inter'),'Inter','DM Sans','Manrope','Montserrat','Poppins','Playfair Display','Cormorant Garamond','Bebas Neue','Arial','Georgia','Verdana'])];
  const importedFonts=imported.flatMap(p=>fontFamiliesFromClone(p.rawHtml));
  const faces=fontFacesFromHtml(imported.map(p=>p.rawHtml).join('\n'));
  const root='/preview/'+store.slug;
  const deviceIcons={Desktop:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>',Tablet:'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M11 18h2"/>',Mobile:'<rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/>'};
  const colors=[['paper','Background','#ffffff'],['ink','Text','#202223'],['surface','Cards and sections','#f6f6f6'],['primary','Solid button','#202223'],['buttonText','Button label','#ffffff'],['secondary','Accent / announcement','#555555'],['border','Borders','#d9d9d9']] as const;
  const colorRows=colors.map(([key,label,fallback])=>{const value=String(brand[key]||fallback);return `<label class="theme-color-row"><span>${label}</span><span class="theme-color-input"><input type="color" aria-label="${label} color" data-color="${key}" value="${value}"><input name="${key}" aria-label="${label} hex" value="${value}" pattern="#[0-9a-fA-F]{6}" maxlength="7" spellcheck="false" required></span></label>`}).join('');
  const fontCard=(role:'display'|'body',label:string)=>{const font=chosenFont(brand[role+'Font' as 'displayFont'],role==='display'?'Playfair Display':'Inter'),weight=Number(brand[role+'Weight' as 'displayWeight'])||(role==='display'?400:400);return `<section class="theme-font-card"><div class="theme-setting-heading"><strong>${label}</strong><button type="button" class="btn" data-font-open="${role}">Change</button></div><input type="hidden" name="${role}Font" value="${e(font)}"><div class="theme-font-sample" data-font-sample="${role}" style="font-family:'${e(font)}';font-weight:${weight}">${role==='display'?'Your next favorite thing':'Good design makes everyday life better.'}</div><span class="theme-font-name" data-font-name="${role}">${e(font)}</span><label class="theme-weight">Font thickness<select name="${role}Weight" aria-label="${label} font thickness">${[[100,'Thin'],[200,'Extra light'],[300,'Light'],[400,'Regular'],[500,'Medium'],[600,'Semibold'],[700,'Bold'],[800,'Extra bold'],[900,'Black']].map(([value,name])=>`<option value="${value}" ${weight===value?'selected':''}>${name} · ${value}</option>`).join('')}</select></label></section>`};
  const field=(key:string,label:string,value:string,area=false)=>`<label class="theme-field">${label}${area?`<textarea name="${key}" rows="4">${e(value)}</textarea>`:`<input name="${key}" value="${e(value)}">`}</label>`;
  const dirty=JSON.stringify(draft.brand)!==JSON.stringify(live.brand)||JSON.stringify(draft.theme)!==JSON.stringify(live.theme);
  const settings=JSON.stringify({source,brand,imported:!!imported.length,fonts:families,importedFonts}).replace(/</g,'\\u003c');
  return `${fontLink(brand,families.filter(f=>!importedFonts.includes(f)))}<style>${faces}${readFileSync(new URL('./theme-editor.css',import.meta.url),'utf8')}</style>
  <header class="theme-page-head"><div><a class="theme-back" href="/admin">← Home</a><h1>Theme settings</h1><p>${e(store.name)} <span>· ${dirty?'Draft has changes':'Draft matches live'}</span></p></div><div class="theme-actions"><a class="btn" href="${root}" target="_blank" rel="noopener">Preview ↗</a>${home?`<a class="btn" href="/admin/pages/${e(home.id)}/edit">Edit page</a>`:''}<button type="submit" class="btn primary" form="theme-form">Save draft</button></div></header>
  <div class="theme-workbench"><form method="post" action="/admin/theme" id="theme-form" class="theme-settings-panel"><div class="theme-panel-title"><strong>Site appearance</strong><span id="theme-save-state">Changes stay in draft</span></div>
  <input type="hidden" name="sourceTheme" value="${e(JSON.stringify(source))}"><input type="hidden" name="fonts" value="${e(families.join('\n'))}">
  <details class="theme-setting-group" open><summary>Colors <span>◐</span></summary><div class="theme-group-body"><div class="theme-setting-heading"><p id="theme-source-label">${imported.length?'From your imported site':'Your site color scheme'}</p>${imported.length?'<button type="button" class="theme-text-button" id="theme-source-colors">Reset to source</button>':''}</div><div class="theme-scheme-card" aria-label="Color scheme preview"><span>COLOR SCHEME</span><h3>Your brand, everywhere.</h3><p>Simple, consistent colors across your site.</p><span class="theme-scheme-button">Shop the collection</span></div>${colorRows}</div></details>
  <details class="theme-setting-group" open><summary>Typography <span>Aa</span></summary><div class="theme-group-body">${fontCard('display','Display / headings')}${fontCard('body','Body')}<p class="theme-help">Preview each font before choosing it. Thickness controls how light or bold it appears.</p></div></details>
  <details class="theme-setting-group"><summary>Layout <span>▤</span></summary><div class="theme-group-body">${home?.mode==='html'?`<input type="hidden" name="template" value="${e(draft.theme.template)}"><p class="theme-help">Your imported page keeps its layout. Use Edit page to change sections, spacing, and columns.</p>`:`<label class="theme-field">Template<select name="template">${['atelier','gallery','market'].map(v=>`<option ${draft.theme.template===v?'selected':''}>${v}</option>`).join('')}</select></label>`}<label class="theme-field">Corner radius<select name="radius">${['0px','2px','8px','16px','999px'].map(v=>`<option ${v===draft.theme.radius?'selected':''}>${v}</option>`).join('')}</select></label><label class="theme-field">Spacing<select name="density">${['roomy','compact'].map(v=>`<option ${v===draft.theme.density?'selected':''}>${v}</option>`).join('')}</select></label></div></details>
  <details class="theme-setting-group"><summary>Brand and home <span>⌂</span></summary><div class="theme-group-body">${field('logoSvg','Logo image URL',brand.logoSvg||'')}${field('slogan','Slogan',brand.slogan||'')}${field('description','Brand description',brand.description||'',true)}${field('announcement','Announcement',brand.announcement||'')}${field('heroHeadline','Hero headline',draft.theme.heroHeadline||'')}${field('heroSub','Hero subheading',draft.theme.heroSub||'')}${field('heroImage','Hero image URL',draft.theme.heroImage||'')}<p class="theme-help">Built-in home settings apply to generated pages. Edit imported content on its page.</p></div></details>
  <details class="theme-setting-group"><summary>Navigation <span>☰</span></summary><div class="theme-group-body">${field('nav','Menu links · Label | /path',draft.theme.nav.map(n=>n.label+'|'+n.href).join('\n'),true)}${field('sections','Built-in home sections',draft.theme.sections.join('\n'),true)}</div></details></form>
  <section class="theme-live-preview"><div class="theme-preview-toolbar"><select id="designer-page" aria-label="Page to preview"><option value="${root}">Home</option>${pages.filter(p=>!p.isHome).map(p=>`<option value="${root}/pages/${e(p.handle)}">${e(p.title)}</option>`).join('')}</select><div class="theme-preview-devices theme-segmented" role="group" aria-label="Preview size">${(['Desktop','Tablet','Mobile'] as const).map((name,i)=>`<button type="button" data-designer-width="${[1200,820,390][i]}" class="${i===0?'on':''}" aria-pressed="${i===0}" aria-label="${name} preview"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${deviceIcons[name]}</svg><span>${name}</span></button>`).join('')}</div><div class="theme-environments theme-segmented" role="group" aria-label="Theme version"><button type="button" data-theme-version="draft" class="on" aria-pressed="true">Draft</button><button type="button" data-theme-version="live" aria-pressed="false" ${live.publishedAt?'':'disabled title="Publish your first theme to compare it here"'}><i></i>Live</button></div><span id="theme-preview-status">Desktop</span></div><div class="theme-preview-stage"><div id="theme-frame-shell"><iframe id="designer-preview" src="${root}" title="Store preview"></iframe></div></div></section></div>
  <div class="theme-footer"><p class="theme-versions"><span><i></i> Draft <b>v${draft.version}</b></span><span class="live"><i></i> Live <b>v${live.version}</b></span></p><div class="theme-actions"><form method="post" action="/admin/rollback"><button class="btn">Discard draft</button></form><form method="post" action="/admin/publish"><button class="btn primary">Publish theme</button></form></div></div>
  <details class="card theme-code"><summary>Custom code</summary><form method="post" action="/admin/theme/code">${field('customCss','CSS',draft.theme.customCss||'',true)}${field('customJs','JavaScript',draft.theme.customJs||'',true)}<button class="btn" type="submit">Save code to draft</button></form></details>
  <dialog class="theme-font-dialog" id="theme-font-dialog"><div class="theme-font-dialog-head"><div><h2>Choose a font</h2><p id="theme-font-dialog-role">Display / headings</p></div><button type="button" class="btn" id="theme-font-close" aria-label="Close font picker">✕</button></div><input type="search" id="theme-font-search" placeholder="Search fonts…" aria-label="Search fonts"><div class="theme-font-list" id="theme-font-list"></div></dialog>
  <script>window.__THEME_EDITOR=${settings};${sourceThemeScript}\n${readFileSync(new URL('./theme-editor.js',import.meta.url),'utf8')}</script>`;
}
